### ISSUE TITLE
Color Management: `colorspace` not parsed properly in some places

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1017]
A few things found while reviewing colour management support.  Could be more.

1. The default value of "none" is not supported. It is being tested as a color space for shader generation.
2. Surface shader node creation does not consider inheritance of `colorspace` (uses `getColorSpace()` vs `getActiveColorSpace()`).
3. Shader translators and texture baker also do not consider inheritance. Also includes using `getActiveColorSpace()` even at document level I believe if there are include files.

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @kwokcb, and I believe we've made good progress on these colorspace limitations in PR #1900.  I'll close out this original report as resolved, but feel free to post new issues as you run into them in MaterialX 1.39 and beyond.
