### ISSUE TITLE
MaterialXView can not represent a small Subsurface Scale

### ISSUE THREAD

**Issue by DADA246c** [AcademySoftwareFoundation/MaterialX#1036]
MaterialXView can not represent a small Subsurface Scale such as 0.01 because mfp is limited to 0.1.

([mx_integrate_burley_diffusion](https://github.com/AcademySoftwareFoundation/MaterialX/blob/a255e89372e768b806c63104336dd5e67edf24fc/libraries/pbrlib/genglsl/lib/mx_microfacet_diffuse.glsl#L60))
vec3 shape = vec3(1.0) / max(mfp, 0.1);

All screen shots are
-Indirect Lighting OFF

Subsurface Scale = 0.1
![image](https://user-images.githubusercontent.com/65879515/181444686-ef62699e-7c00-449e-9601-ca59d068cb88.png)

Subsurface Scale = 0.01 (Same results as Subsurface Scale = 0.1)
![image](https://user-images.githubusercontent.com/65879515/181444801-845ba89d-9f18-4938-b75e-fce075b37bf8.png)

If mfp is not limited to 0.1, MaterialX can represent a small Subsurface Scale.

vec3 shape = vec3(1.0) / max(mfp, M_FLOAT_EPS);

Subsurface Scale = 0.1
![image](https://user-images.githubusercontent.com/65879515/181444852-87491a83-90b1-407a-b6ed-eef97105d105.png)

Subsurface Scale = 0.01 
![image](https://user-images.githubusercontent.com/65879515/181444895-98805958-e15f-4bf8-bfcf-919bc8cdef0c.png)

**Comment by jstone-lucasfilm** [comment]
This is a good observation, thanks @DADA246c, and I think it's worthwhile to adjust this minimum value.

Experimentally, I'm seeing correct visual behavior when I reduce the minimum value from 0.1 to 0.01, but I see numerical artifacts at grazing angles when I reduce it to 0.001.  Based on that initial data, it seems reasonable to me that the minimum value should be changed to 0.01 to support a wider range of subsurface scales.

If that sounds reasonable to you, would you have the bandwidth to give this a try, and write up a pull request if the change works for you as well?

**Comment by DADA246c** [comment]
Thank you for your reply. @jstone-lucasfilm 
The reason why I set the subsurface_scale to 0.01 is that I thought that the subsurface_scale would be about 1 cm for human skin (the unit is 1 as 1 meter).
I've investigated what causes the rendered result to be black when subsurface_scale is set to a small value.

In [mx_integrate_burley_diffusion](https://github.com/AcademySoftwareFoundation/MaterialX/blob/322bf9bd9dc5be6265d7ead677737f36d294458e/libraries/pbrlib/genglsl/lib/mx_microfacet_diffuse.glsl#L55), a small subsurface_scale results in a small value for mfp, and [the shape variable](https://github.com/AcademySoftwareFoundation/MaterialX/blob/322bf9bd9dc5be6265d7ead677737f36d294458e/libraries/pbrlib/genglsl/lib/mx_microfacet_diffuse.glsl#L60) is large.
Since the shape variable is a large value, the result of the [exp function](https://github.com/AcademySoftwareFoundation/MaterialX/blob/322bf9bd9dc5be6265d7ead677737f36d294458e/libraries/pbrlib/genglsl/lib/mx_microfacet_diffuse.glsl#L47) in mx_burley_diffusion_profile will be zero by floating point precision.

For example
subsurface_scale = 0.0001
shape = 10000
exp(-10000) = 0 //floating point precision

As a result, [R](https://github.com/AcademySoftwareFoundation/MaterialX/blob/322bf9bd9dc5be6265d7ead677737f36d294458e/libraries/pbrlib/genglsl/lib/mx_microfacet_diffuse.glsl#L71) in mx_integrate_burley_diffusion becomes 0, [sumD / sumR](https://github.com/AcademySoftwareFoundation/MaterialX/blob/322bf9bd9dc5be6265d7ead677737f36d294458e/libraries/pbrlib/genglsl/lib/mx_microfacet_diffuse.glsl#L76) causes division by 0, and mx_integrate_burley_diffusion returns 0.
To solve this problem, I am investigating setting the precision of the exp function to double, etc, but I have not been able to solve it yet.
