### ISSUE TITLE
Add 1.39 <separatecolor4> definition

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1050]
Adding in an issue to add this definition which is already agreed to be added for the 1.39 specification.
A common case is to separate out the RGB and A channels from an RGBA texture.

Draft spec interface is as follows:

*separatecolor4*: output the RGB and alpha channels of a color4 as separate outputs.
*  `in` (color4): the input value or nodename
* `outcolor` (output, color3): the RGB channel values.
* `outa` (output, float): the value of the alpha channel.

Note: this can be implemented as 2 `<swizzles>`

**Comment by jstone-lucasfilm** [comment]
I'll close out this issue for now, as the <separatecolor4> node is still just a suggestion in the 1.39 specification.  We can bring back this proposal as the specification gets closer to release.
