### ISSUE TITLE
Coat is partially unaffected by Emission in MaterialXView

### ISSUE THREAD

**Issue by DADA246c** [AcademySoftwareFoundation/MaterialX#1057]
[SurfaceNodeGlsl::emitFunctionCall](https://github.com/AcademySoftwareFoundation/MaterialX/blob/322bf9bd9dc5be6265d7ead677737f36d294458e/source/MaterialXGenGlsl/Nodes/SurfaceNodeGlsl.cpp#L177) adds Emission after direct lighting calculation, so Coat is not taking partial effect of Emission.

At Standard Surface, Emission is affected by Coat.
![image](https://user-images.githubusercontent.com/65879515/185866921-7b6458a3-5fd4-45bf-97be-bd6a010662b1.png)

I think the current implementation is shown below.
![image](https://user-images.githubusercontent.com/65879515/185867001-7844ea1f-c8d8-4355-825d-c642a4c86bdc.png)

MaterialXView
Indirect Lighting OFF
Render Environment OFF
Specular 0

Coat 0 , Base 0.5 , Emission 0
![image](https://user-images.githubusercontent.com/65879515/185867247-da0ea81d-7793-42eb-ae66-8ed52bf3e33c.png)

Coat 1 , Base 0.5 , Emission 0 
Coat darkens the mesh outlines.
![image](https://user-images.githubusercontent.com/65879515/185867324-14f25cdf-5ee0-449e-bdeb-0d00cc6bdaaa.png)

Coat 0 , Emission 0.5 , Base 0
![image](https://user-images.githubusercontent.com/65879515/185867533-85204069-114e-46ed-a19c-95716b4e3dc1.png)

Coat 1 , Emission 0.5 , Base 0
The mesh outlines are not darkened.
![image](https://user-images.githubusercontent.com/65879515/185867589-66e5e2aa-100a-42cd-8e4d-e4fd8f46fd01.png)

**Comment by DADA246c** [comment]
Thanks for the reply.
I understood the reasons.

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @DADA246c, and this has been addressed by @niklasharrysson in #1262.
