### ISSUE TITLE
Make it easier to run python tests

### ISSUE THREAD

**Issue by pmolodo** [AcademySoftwareFoundation/MaterialX#1078]
At the moment, the only source of the "complete" set of python tests seems to be in `.github/workflows/main.yml`, under the `Python Tests` step.

It would be nice if this were extracted into it's own standalone script, or similar, to enable easier running outside of github.  Also, I'm not clear on how github detects failure for many of these tests - ie, `Scripts/generateshader.py` seems to swallow many errors, and return `0`, so I was forced to scrape output for `Failed` strings.

**Comment by jstone-lucasfilm** [comment]
These are good suggestions, @pmolodo, and I'll note that the error reporting in `generateshader` should be improved by the recent merge of #1160.

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @pmolodo, and I believe there have been enough refinements to our Python tests that it makes sense to close this out, with additional requests for improvements being made in new GitHub Issues.
