### ISSUE TITLE
GLSL shader uniform parsing bottleneck in WebGL

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1092]
## The Bottleneck

After some digging it appears that almost all the time for setting up the raw shaders created by MaterialX in WebGL
is taken up by uniform introspection. The more shaders the slower it gets. 

Not sure why it is so bad compared to introspection done on desktop GL but this can cause the appearance of "hangs" due to just this one item. All other setup appears to be about 1 or less than 1% of the time.
Apparently this is known issue and seems that it should be better with WebGPU.

This is the code in question:
```javascript
class WebGLUniforms {

	constructor( gl, program ) {

		this.seq = [];
		this.map = {};

		var st = performance.now();
		const n = gl.getProgramParameter( program, 35718 );
		console.log("* getProgramParameter time", 	performance.now() - st);

		for ( let i = 0; i < n; ++ i ) {
			const info = gl.getActiveUniform( program, i ),
				addr = gl.getUniformLocation( program, info.name );

			parseUniform( info, addr, this );
		}
     }
```
The performance probes were added in to the code.

It could be due to the number of uniforms to parse for something like std surface but it seems it should not be
that bad. There are 55 exposed uniforms for an unmapped std surface. As an example the chessboard scene can take about 3 or more minutes to parse uniforms. Another test with about 8 std surface shaders also take about the same
amount of time.

This is information, without a concrete proposal on how to address this. I would be curious to know how this performs for other Web integrations, but it seems the AMD GPUOpen prep time is also slow and could be gated by this. 

Note that the performance of editing uniforms and executing the shader is negligible in comparison to this parsing time.
Note2: this is on a Windows 10 Machine with an RTX 2060. On a Mac M1 the parsing speed is about 10x faster -- so use a Mac ? :).

## Workaround
This is not a good workaround but if you encapsulate at least standard surface (bxdf) and other associated nodes into a nodegraph and create a nodedef from it and only expose the required inputs then time will substantially drop.
Note that the code generation options need to be set to "reduced" -- i.e.  
```
GenOptions.shaderInterfaceType = MaterialX.ShaderInterfaceType.SHADER_INTERFACE_REDUCED
```
In current tests, time dropped from 5 minutes to 5 seconds. for 12 std surf shaders with upstream color + normal maps on Windows. There is some small percentage gain on Mac.

## Possible Additions
It could be useful to have an additional shader-gen option(s) to 
1. only expose uniforms for non-default values and /or 
2. only expose published inputs on nodegraphs. 
This reduces editability however but is good for sending to renderers.

**Comment by kwokcb** [comment]
@ashwinbhat , @jstone-lucasfilm pinging you for reference as this is "part 2" of my performance investigation.
Perhaps this could be passed on to others for insight as this is the #1 bottleneck for scene load and as larger scenes are tried with more shaders load times will become untenable.

**Comment by kwokcb** [comment]
Adding an additional note after a chat with @ashwinbhat :
* Uniform block support support could help here.
* Being able to have custom named blocks would also help long term (should be separate requrest issue)

Also trying wrapping brick shader reduces the uniform count from 106 to 16 so worth considering as part 
recommendations for "information hiding".

**Comment by jstone-lucasfilm** [comment]
Following on this issue in 2024, our main bottlenecks for WebGL render performance appear to be related to shader math/ALU complexity rather than shader uniform parsing, so I'll mark this original issue as resolved.
