### ISSUE TITLE
MaterialX dlls are missing version information

### ISSUE THREAD

**Issue by ashwinbhat** [AcademySoftwareFoundation/MaterialX#1102]
When built as dynamic dlls on Windows, MaterialX dlls are missing version information.
![image](https://user-images.githubusercontent.com/1727158/195204053-f8b3924a-9750-4a9e-b2f5-218cf97d8bd3.png)

Probably need some Cmake work to enable this.

```[tasklist]
### Tasks
- [ ] https://github.com/AcademySoftwareFoundation/MaterialX/pull/1447
```

**Comment by jstone-lucasfilm** [comment]
Addressed in #1447, thanks to @ashwinbhat for the fix!
