### ISSUE TITLE
Handle naming conflicts in MaterialX source includes for OSL 

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1110]
Currently there is an `mx_funcs.h` as well as other include files with some custom identifiers and functions.

When included in code their names could cause generated code to conflict with it.
An example is logged here (https://github.com/AcademySoftwareFoundation/MaterialX/issues/1106) for instance.

The current proposal is to at least rename possible conflicts to start with `mx_` consistently, though the side-effects of this
are unknown. This is a similar naming approach taken in general for "MaterialX" source code additions.

Additionally these names need to be added to the [list of restricted keywords in for OSL](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/source/MaterialXGenOsl/OslSyntax.cpp)

This causes a unique name to be generated. Note that if this is for reference implementation generation and an 
a definition's argument identifier conflicts it will be renamed, and hence will no longer match the nodedef's input name.
This is a orthogonal issue brought up to have control over this naming but conflicts must still be avoided.

Note that some of these would not be required and should be removed if they become intrinsics (color4 seems to be in the plan)
to avoid conflict with intrinsics.

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @kwokcb, and this issue has been addressed as part of #1184.
