### ISSUE TITLE
Matrix coefficient differences relative to ACES

### ISSUE THREAD

**Issue by doug-walker** [AcademySoftwareFoundation/MaterialX#1120]
Currently, MaterialX has the following, in libraries/stdlib/genglsl/lib/mx_transform_color.glsl:

#define M_AP1_TO_REC709 mat3(1.705079555511475, -0.1297005265951157, -0.02416634373366833, -0.6242334842681885, 1.138468623161316, -0.1246141716837883, -0.0808461606502533, -0.008768022060394287, 1.148780584335327)

It appears that this may have been calculated using the CAT02 chromatic adaptation transform rather than the Bradford transform used by ACES.  In other words, the above matrix will result in a slight difference between MaterialX's internal default color management system and what an OCIO ACES config would produce.  The coefficients that would match ACES are:

1.705050992658, -0.130256417507, -0.024003356805,
-0.621792120657,  1.140804736575, -0.128968976065,
-0.083258872001, -0.010548319068,  1.15297233287

**Comment by jstone-lucasfilm** [comment]
Good catch, @doug-walker, and thanks for the detailed analysis!  Feel free to write up a pull request if you have the bandwidth; otherwise we'll address this on our side.

**Comment by jstone-lucasfilm** [comment]
Thanks for reporting this, @doug-walker, and this issue has been addressed in #1163.
