### ISSUE TITLE
Texture baking output access for multiple material documents

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1140]
## Issue
Currently `TextureBaker` always writes out a new document per material found. 

1. It is very hard to find the output documents. 
The only indication as to where these files are is output to a given stream like std out and no way to access them in-memory.
2. It is very hard to merge these documents together afterwards as unique naming is per document so things like the upstream bake nodegraph are duplicated (`NG_graph`) and / or `geompropvalues`

## Suggestions
1. Add an option to write to a single output document as an option.
2. Add an option to write to disk separately and have access to in-memory document(s).
(It would be useful to not always write the image cache to disk as well and have access to that).

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @kwokcb, and I'll close this out now that #1141 has been merged.
