### ISSUE TITLE
Suggestion: Rename "gltf_pbr" to "pbr_next"

### ISSUE THREAD

**Issue by bhouston** [AcademySoftwareFoundation/MaterialX#1145]
Re this file:

https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/libraries/bxdf/gltf_pbr.mtlx

The formal name for the glTF consolidated PBR BSDF root node is actually "PBR Next".  You can see that name used in these publications/press releases:

* https://www.khronos.org/news/press/khronos-releases-wave-of-new-gltf-pbr-3d-material-capabilities
* https://github.com/KhronosGroup/glTF/milestone/2
* https://www.rapidcompact.com/pbr-next-support/
* https://www.khronos.org/news/press/new-gltf-extensions-raise-the-bar-on-3d-asset-visual-realism

I would strongly suggest that we move away from the name glTF in the definition to just calling it PBR_Next.

This is in part to feedback I got from Guido Quaroni at a recent talk at the RTC conference, which was also attended by ASF's David Morin.  Basically Guido said we would see larger adoption of this BSDF if it wasn't specifically tied to glTF only.

As such I am suggesting this name change.

@pjcozzi @jstone-lucasfilm @pablode @proog128 @kwokcb

**Comment by jstone-lucasfilm** [comment]
Thanks for this proposal, @bhouston.  I'm interested in thoughts from stakeholders at Khronos, and I'll just note that this change would be straightforward from a technical perspective.  MaterialX nodes can be renamed with each new specification version (e.g. 1.38 -> 1.39), and there is infrastructure in place to handle the upgrade of assets referencing the original node names.

**Comment by emackey** [comment]
I don't think `pbr_next` is the right answer here.  "PBR Next" was a working title for a sub-group within Khronos that formed in June of 2020, and by November of the same year the group became official under the name "PBR TSG" (Task Sub-Group in Khronos lingo) with myself as Chair of the TSG.  Recently as it became clear that our flavor of PBR can and should exist outside of glTF, we've struggled to agree on a better name for the new specification.

The current draft bears the title "Khronos PBR", sometimes written as "Khronos® PBR" or "The Khronos® PBR Specification."  I don't know if this name is the final answer, but it seems more likely to withstand criticism than some of the other suggestions.

Could the MaterialX node be named `<khronos_pbr>`?  There's an upcoming meeting in about two weeks where this topic may generate additional discussion.

**Comment by kwokcb** [comment]
Hi @emackey, 
As mentioned it can be renamed to whatever seems best pretty easily.
`<khronos_pbr>` does sound like a good candidate.

**Comment by jstone-lucasfilm** [comment]
@emackey Just as an outside perspective, I like your proposal to name the shading model `khronos_pbr`, which would be clearly associated with Khronos Group and unique in the space of popular models.

**Comment by jstone-lucasfilm** [comment]
I'll close out this proposal for now, but let us know if Khronos Group decides on a new name for this shading model in the future, and we'd be happy to integrate this change into the MaterialX data libraries, along with version upgrade logic to handle assets referencing the original name.
