### ISSUE TITLE
add custom osl to Materialx

### ISSUE THREAD

**Issue by xZAKHAMx** [AcademySoftwareFoundation/MaterialX#1154]
testing MaterialX on Houdini and my question is, can i add custom osl shaders to MaterialX lib without rebuilding MaterialX libs for Houdini again? if yes, how?
If no, so what i should do to add a custom nodes to MaterialX and able to use it inside Solaris VOP network or any other software?

**Comment by jstone-lucasfilm** [comment]
Hello!  This would definitely be a question for the Houdini team, and I'd recommend asking it either on a SideFX forum or the MaterialX channel of the ASWF Slack, where members of the Houdini team are often present:

https://www.aswf.io/get-involved/

**Comment by jstone-lucasfilm** [comment]
I'll close out this GitHub Issue, as there's now an active discussion between @xZAKHAMx and the Houdini team on the ASWF Slack.
