### ISSUE TITLE
Installation and requirement of 'resources' directory

### ISSUE THREAD

**Issue by pablode** [AcademySoftwareFoundation/MaterialX#1167]
Hello! When installing MaterialX, f.i. by [building USD with MaterialX](https://github.com/pablode/USD/releases), the 'resources' directory is installed, too.

It's pretty large (130MB+) and it's required by the [MaterialXConfig.cmake.in](https://github.com/AcademySoftwareFoundation/MaterialX/blob/e2bb3898272868115042327d00c0065baf3477d6/cmake/modules/MaterialXConfig.cmake.in#L25) file when trying to link against MaterialX.

Since this folder is not needed by the runtime, unlike the libraries folder, would it be possible to make the installation of this folder optional?

For instance, it could be installed if either `MATERIALX_BUILD_VIEWER` or `MATERIALX_BUILD_TESTS` is set to `ON`.

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @pablode, and I think checking the `MATERIALX_BUILD_VIEWER` and `MATERIALX_BUILD_TESTS` options before installing the resources folder is a good proposal.  Would you have the bandwidth to implement this fix on your side?

**Comment by kwokcb** [comment]
These could be used outside of the view or tests so suggest a new `MATERIALX_INSTALL_RESOURCES` flag is better.

**Comment by benjaminbeilharz** [comment]
Hi guys, I am new to the project, but can take a look at it.
