### ISSUE TITLE
Minor: Improper warning when input uses defaultgeomprop 

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1192]
The validation gives a warning when an input has `defaultgeomprop` set but no value.
Believe this should not be considered invalid. Example output
```
Node input binds no value or connection: <input name="normal" type="vector3" defaultgeomprop="Nworld">
Node input binds no value or connection: <input name="tangent" type="vector3" defaultgeomprop="Tworld"
```

**Comment by jstone-lucasfilm** [comment]
That's a good observation, @kwokcb, but isn't `defaultgeomprop` only supported for NodeDef inputs, and not for Node inputs?  If that's the case, then this warning should never be emitted for a valid use of `defaultgeomprop`:

https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/source/MaterialXCore/Interface.cpp#L341

**Comment by jstone-lucasfilm** [comment]
@kwokcb It sounds like this warning message is correct, in which case this issue should be closed, but let me know if there's a subtle detail that I'm missing.
