### ISSUE TITLE
MaterialXEditor: UI Sug to have hot-key help 

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1210]
Nothing is broken here but a sug for usability. (Though I can't get delete to work on Mac, but seems okay on Windows)

It would be useful to have some way to know what hot-keys are available as it's hard to figure just by pressing keys :).
E.g. tabbing between fields in the property editor is CTRL-<arrow keys>. (Was trying to tab but that brings up the "add node"
popup.

Additional sug is that it would be nice to have the keys labelled on the menus when that is available.

This seems to  be the list, but I needed to search code :).
* Also found U to go up from a sub-graph by accident.
* F and CTRL-F are more obvious for frame and search
* CTRL-X / Delete key, CTRL-C, CTRL-V
* CTRL-<arrow> 
 
As a small note, for Mac:
- the Delete key does not seem to work on Mac (i.e. seems to do nothing?)
- and it's a bit "unnatural" to not support the Command keys vs the Ctrl keys there.

**Comment by jstone-lucasfilm** [comment]
@kwokcb For help on hotkeys, I'd definitely recommend the Graph Editor documentation, and feel free to propose improvements there:

https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/documents/DeveloperGuide/GraphEditor.md#keyboard-shortcuts

For the Delete key on macOS, that sounds like a worthwhile issue to investigate, but I'd recommend making this a separate issue, or addressing the bug directly if you have the bandwidth.
