### ISSUE TITLE
MaterialXEditor : Can crash on invalid file load / lack of filtering 

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1211]
Exceptions don't seem to be caught on file load so will crash the editor.
It would be good to add in this check here, and maybe other places where an exception can be thrown.

As a sug, it would be useful to add in file type filtering as I tried to load in an image as a mtlx file.
e.g. add something like this in on load and save:
```
    mx::StringVec mtlxFilter;
    mtlxFilter.push_back(".mtlx");

    _fileDialog.SetTypeFilters(mtlxFilter);
    _fileDialogSave.SetTypeFilters(mtlxFilter);
```

**Comment by jstone-lucasfilm** [comment]
Thanks for addressing these issues in #1218, @kwokcb, and I'll mark the original report as closed.
