### ISSUE TITLE
MaterialXEditor: Nodes with multi-outputs only show 1 output

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1212]
For some reason, if you create a node which which has multiple outputs, only 1 output shows, and 
I don't think it's connectable. e.g. UsdUVexture has 4 outputs but only 1 shows up.
Unsure if this is only for those that use functional nodegraphs or not.

**Comment by jstone-lucasfilm** [comment]
That's a good observation, @kwokcb, and we're already tracking this issue in the Known Limitations section of the Graph Editor documentation:

https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/documents/DeveloperGuide/GraphEditor.md#known-limitations
