### ISSUE TITLE
MaterialXEditor Sug: Would be useful to handle high dpi

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1213]
The doesn't seem to be any high dpi handling so the UI, esp fonts can appear very small.
It seems imgui is not well set up for this, but assume folks have something out there.

Here is a snapshot (4K monitor) between the editor and a [site](https://floooh.github.io/sokol-html5/imgui-highdpi-sapp.html) 
that seems to do scaling properly.

![image](https://user-images.githubusercontent.com/49369885/216139697-3badd9c1-7319-476f-84ab-0e6133c105de.png)

Seems `ScaleAllSizes()` could be the thing to call after finding the DPI scaling. Is mentioned [here](https://github.com/ocornut/imgui/issues/5452) for instance.

Would be nice to look at for the sake of my bad eyes but maybe others as well :).

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @kwokcb, as well as for the fix in #1248!
