### ISSUE TITLE
Graph Editor: Scroll wheel zooms and scrolls property editor

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1214]
A minor nitpick. When the editor has a scroll bar on the right (show all inputs for std surface), if you use the scroll
wheel it will zoom in / out on the preview window but also scroll at the same time so it makes it hard to be able to zoom.

https://user-images.githubusercontent.com/49369885/216150266-3c1f1766-ba0c-4a83-b0fc-03fc580914b8.mp4

Looks like some minor pointer focus / handling issue that the event once handled by the preview window should not be passed onwards back to the scrollbar ?

**Comment by lfl-eholthouser** [comment]
Thanks for pointing this out @bernardkwok ! The render view zoom only checks right now if the cursor is within the bounds of the render view window which is causing that issue.

**Comment by kwokcb** [comment]
There are 3 scroll areas. The entire panel, the renderview, and just the attribute list. Each should trigger different behaviour. Only the panel scroll bar seems to affect the renderview.

**Comment by benjaminbeilharz** [comment]
Thanks @kwokcb I'll take a look.

**Comment by jstone-lucasfilm** [comment]
Thanks to @kwokcb for reporting this issue, and to @HudsonHN for the fix in #1578!
