### ISSUE TITLE
MaterialXEditor: Query -- How should multiple material assignments work?

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1216]
If you load in a file with multiple materials, then on load it shows the materials assigned to the geometry
properly. After you choose a specific material only that material shows up. This makes sense as that's
the material in focus. 

There however does not seem to be anyway to see all the materials again. 

I assume it's a slippery slope to deal with material assignments here as they are in l`ook`s, and `materialassign`s both of
which are not even considered "nodes". So leaving this as more of a query on what is appropriate here ?
Perhaps only 1 material should ever show up for now to avoid adding more complexity ?

Try the example brass example using looks.

**Comment by jstone-lucasfilm** [comment]
Good points, @kwokcb, and I think your suggestion is a good one.

Making the Graph Editor distinct from the Viewer, we could impose the simplification that only a single material is ever rendered on the model in the viewport, and the user can switch between them (as is currently the case) by clicking on the corresponding nodes in the graph window.

**Comment by kwokcb** [comment]
This sounds good.

This can be raised as a separate issue:
------------------------------------------
Could I suggest the "flips-side" to this, in that it's a bit strange that there is a material being drawn when there is no node-graph. I see as a simplifying possibility to have an actual default surface+material on startup. and / or not draw anything at all
which could be the easiest logic.  

Currently if you have no materials in a graph, the last graph is left to render -- this feels confusing. Even clearing using
"New Material" does not clear the rendering.

Example of graph created then cleared but still rendering (my GPU is pegged at 40% without a graph)
![image](https://user-images.githubusercontent.com/49369885/216706396-f4720189-0ca1-4260-a2a8-485fc7f97ba9.png)

**Comment by kwokcb** [comment]
@jstone-lucasfilm This should be fixed now with the material update merge.

**Comment by jstone-lucasfilm** [comment]
Great, and thanks for those improvements!
