### ISSUE TITLE
MaterialEditor: Material Preview does no update on deletion of shader

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1217]
If you have a simple setup of a shader->surfacematerial, modify the shader and then delete it,
the preview does not update. Seems to be leaving around the last material rendered.

e.g. here the color of a shader was change to blue from (default) white, and deleted.
![image](https://user-images.githubusercontent.com/49369885/216165265-9057f842-1495-4b46-bfa1-22fb96282e86.png)

**Comment by kwokcb** [comment]
@jstone-lucasfilm This should be fixed now with the material update merge.

**Comment by jstone-lucasfilm** [comment]
Thanks @kwokcb, and I'll close this issue out.
