### ISSUE TITLE
MaterialXEditor: nodes with multiple outputs only create 1 output for nodes

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1220]
This occurs on load and on tab creation.
Issues appears to be when creating pins. A single pin is always assumed of type of the node. Nodegraphs seem fine.
If the node type is multioutput then an unconnectable output appears to be created.

Appears the fix is to add all active outputs from the nodedef as inputs are added in both these locations:
`Graph::addNode()` and `Graph::setUiNodeInfo()`

( I can make this change as it seems to do the trick from early testing. e.g. boombox loads in and UsdUvTexture creates okay)

<img width="909" alt="Screen Shot 2023-02-01 at 11 07 29 PM" src="https://user-images.githubusercontent.com/49369885/216229404-82f967a4-5558-41bc-8396-81538803fba6.png">

**Comment by jstone-lucasfilm** [comment]
That looks really promising, @kwokcb!

**Comment by jstone-lucasfilm** [comment]
Thanks for both the report and the fix, @kwokcb, and I'll close out this issue.
