### ISSUE TITLE
MaterialXEditor: Missing various input and output interface types "nodes"

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1228]
Currently the types of inputs and outputs is fixed and is a subset of the available types (as specified in stdlib_defs.mtlx).
Thus they are missing on load and cannot be created interactively.

This prevents users from creation using graphs with these types of inputs / outputs.
In particular PBR and all shader types are missing, matrix, arrays, geomname, lights and materials.

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @kwokcb, and thanks to @niklasharrysson for the fix!

**Comment by kwokcb** [comment]
Thanks @niklasharrysson for fixing this. I had one more thing that I think would be good to add here.

@jstone-lucasfilm , the 'none' type is no longer used anywhere so I think it should be excluded from being able to be created. I believe it was nixed when `backdrop` stopped being a node, but I think the `typedef` is still required to perform upgrades of older files. Suggest to filter it out so you can't create these?
