### ISSUE TITLE
MaterialXEditor: shader and material nodes cannot be created inside nodegraphs

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1230]
Seems these are always created at the top level even when trying to create them inside a nodegraph.
So you can't create new surface shader graphs and materials in nodegraphs and it's confusing since the UI
shows them in the graph but they are saved in the Document outside the graph.

Seems like a simple fix to remove the code which forces them to be created at the top level.

**Comment by jstone-lucasfilm** [comment]
Closing this issue as it's been addressed in #1231.
