### ISSUE TITLE
MaterialXEditor: fan-in on inputs allowed in UI 

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1232]
Strangely an input can show up with 2 connections on it (fan-in). This does not save out but
is pretty confusing. 

It seems there is a check to see if the pin is connected but this always returns false
as it appears another pin has it's connection set ? This is what was observed in `Graph::AddLink()`
with this check which never seems to return true:
```
if (inputPin._connected == false)
```
Snapshot of example test case. UI allows the fan-in but the document when saved is okay.
![image](https://user-images.githubusercontent.com/49369885/217389530-627f72f5-c0dd-4fce-99d7-6522ac4c6152.png)

**Comment by kwokcb** [comment]
Digging some more I see two things:
1. The Graph keeps a list of 'Pin's but when accessing them, they are accessed as copies instead of references when setting connections. This is for iterators `(for pin : pinlist)` vs `for pin& : pinlist)` and `getPin()`.
2. Even when trying to fix this there still seems to be issues, as when checking for existing connections, every pin in the Graph has no connections?

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @kwokcb, and I believe this issue has been addressed in #1244.
