### ISSUE TITLE
TargetDef API does not exist in Python

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1240]
The `TargetDef` type and API are not exposed in Python.
It is possible to find them but it would be better if the API was added to Python.
Workaround for now is something like this:
```python
def getTargetDefs(doc):
    targets = []
    for element in doc.getChildren():
        if element.getCategory() == 'targetdef':
            targets.append(element.getName())
    return targets
```

A small additional point is that `essl` does not use the "convention" of a prefix of "gen" -- it is called `essl` vs `genessl`.

**Comment by jstone-lucasfilm** [comment]
Closing this issue, as it's now been addressed in #1241.  Thanks @kwokcb!
