### ISSUE TITLE
MaterialXGenShader(ShaderGraph) : Enumeration values do not remap to integers

### ISSUE THREAD

**Issue by MasayaNikaido** [AcademySoftwareFoundation/MaterialX#1268]
When ShaderGraph::create() calls with an element of type **Node**, enumeration input values do not remap to integers.
Is remapEnumeration() necessary here?
https://github.com/AcademySoftwareFoundation/MaterialX/blob/b24e9dd16624fe2d09aa167f03a8154b8589b24e/source/MaterialXGenShader/ShaderGraph.cpp#L730-L737

**Comment by MasayaNikaido** [comment]
Additionally, addDefaultGeomNode() is required here, but inputSocket->makeConnection() is not required in this case.

https://github.com/AcademySoftwareFoundation/MaterialX/blob/b24e9dd16624fe2d09aa167f03a8154b8589b24e/source/MaterialXGenShader/ShaderGraph.cpp#L759-L763

**Comment by niklasharrysson** [comment]
Thank you @MasayaNikaido for reporting these issues. I can reproduce the problem and I'm working on a fix.

**Comment by MasayaNikaido** [comment]
Thank you for your quick improvement. It's working as expected.

**Comment by jstone-lucasfilm** [comment]
Thanks to @MasayaNikaido for this report, and to @niklasharrysson for the fix!
