### ISSUE TITLE
uiname for inputs only seem to work on node def inputs.

### ISSUE THREAD

**Issue by ix-dcourtois** [AcademySoftwareFoundation/MaterialX#1279]
Hi,
Not sure the title is the best, but I wasn't sure how to phrase it, so here is a better description:
I'm creating a simple material graph, and I'd like to customize the ui name of a few inputs. E.g. for instance I have an `image` node named `diffuse`. When loading into MaterialX view, in the property editor the filename of that node would then appear as `diffuse:filename`.
I'd like that to appear as `Diffuse Filename` for instance. So I tried using the `uiname` attribute, but unfortunately: https://github.com/AcademySoftwareFoundation/MaterialX/blob/7228592bedb75492db88018da230c1a852408eeb/source/MaterialXRender/Util.cpp#L110-L113

This will always use the input def, thus ignoring the `uiname` on the attribute itself.
Is this intentional? Would it be acceptable to consider both the input def and the input when extracting UI properties? For instance checking first the input, and if it doesn't have a property, checking the input def? (which would then act kind of a like a default)

**Comment by kwokcb** [comment]
Hi @ix-dcourtois,
According to the spec `uiname` is only defined when on a `nodedef` input.
https://materialx.org/assets/MaterialX.v1.38.Spec.pdf#page=51

But, if your encapsulating things into a `nodegraph`, I think the "best" you can do is to add an interface input connected to an internal node input and use a more "user friendly" name. But, AFAIK, you can't specify a `uiname` on an interface input for a nodegraph either (which seems useful). 

Otherwise the only option, I think is to create a `nodedef` from your `nodegraph`.

**Comment by kwokcb** [comment]
I agree. 

I guess it depends on how complex this can get. For example, can you specify a uiname on a node input and its graph interface. I believe there is nothing new in terms of logic so not hard to understand or implement.

The second item is which ui "things" can you specify. Uiname seems a good first candidate but would need to discuss if others make any sense. For example, dont think you want to allow this at the node level, nor allow attributes like uimin, uimax on instances would you?

Giving a ping to @dbsmythe and @jstone-lucasfilm for thoughts.

**Comment by ix-dcourtois** [comment]
In the case of the `marble`, the input is a node graph input. It doesn't have any corresponding input in a nodedef. And thus the `getUIProperties` will use the actual input, which works.

This is my (simplified) case:
```xml
<?xml version="1.0"?>
<materialx version="1.38">
  <surface name="mx_surface" type="surfaceshader" nodedef="ND_surface">
    <input name="edf" type="EDF" nodename="mx_uniform_edf" />
  </surface>
  <uniform_edf name="mx_uniform_edf" type="EDF" nodedef="ND_uniform_edf">
    <input name="color" type="color3" nodename="diffuse" />
  </uniform_edf>
  <image name="diffuse" type="color3" nodedef="ND_image_color3">
    <input name="file" type="filename" value="D:/Pictures/20180204_105455.jpg" uifolder="Interface" uiname="Diffuse Filename" />
  </image>
  <surfacematerial name="mx_material" type="material">
    <input name="surfaceshader" type="surfaceshader" nodename="mx_surface" />
  </surfacematerial>
</materialx>
```

Here I'm "overridding" the `file` input of an `image` node, which *has* a `nodedef`. So the `getUIProperties` function (which I linked above) will actually get the nodedef input, and use *that* one instead of my customized one.

**Comment by dbsmythe** [comment]
Here's the logic for why things are the way they are now regarding `uiname` and other `ui` attributes:
- If it's a _functional_ nodegraph, e.g. one that has a nodedef to define the interface, then it's presumed that you want this node definition to be reusable and have potentially multiple instantiations of that nodegraph-defined node.  In this case, it doesn't make sense that the UI for one instance of that node has a different UI than another instance of the same node, hence the restriction to not allow `uiname` etc on inputs of functional nodegraphs.
- If it's a _compound_ nodegraph, e.g. one with no corresponding nodedef, then this *is* the definition of the UI for the nodegraph (and the nodegraph can't be instantiated multiple times), so it makes sense to allow `uiname` etc. definitions on the top-level inputs, as is done in the standard_surface_marble_solid.mtlx example.  Note that inputs to nodes _within_ the compound nodegraph may not specify a uiname: those are local to the scope *inside* the nodegraph and are not publicly-accessible: they must instead connect via `interfacename` to the top-level input interface.

Your simplified case above is neither of the above: the nodes are not contained within a nodegraph at all.  In theory, it wouldn't hurt to make it allowable to add `uiname`s on such free-floating non-nodegraph-wrapped inputs, but I fear this could make the coding rules to determine whether a uiname should be allowed on a particular input and which uiname should take precedence a bit tricky.  The current proper thing to do if you want to create a named UI is to wrap your whole example within a (compound) nodegraph, put the UI interface parameter inputs there, and use `interfacename` connections from your node inputs to the interface inputs.  However, I'm open to discussion about whether the community thinks we should allow `uiname` attributes on inputs of free-floating nodes.

**Comment by jstone-lucasfilm** [comment]
@ix-dcourtois From the discussion above, it sounds like the current behavior is expected in MaterialX 1.38, so I'll close out this issue for now.  Going forward, though, we're open to proposals for improved UI name rules in future versions of MaterialX.
