### ISSUE TITLE
Camera Pan for MaterialXView on Mac is inverted

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1287]
Guessing this has to do with the Metal switch ?

If you pan in MaterialXView up / down, then the camera appears to pan in the opposite direction.
Up -> down and down -> up.

Pan on the GraphEditor is okay but that is still using GL.

@Morteeza giving you a ping on this. 
I don't think it's related but I updated to Ventura (13.2.1 (22D68).

**Comment by Morteeza** [comment]
@kwokcb Thanks for letting me know about this issue. Indeed this was related to negation we apply to compensate for frame buffer coord difference between GL and Metal. I created a PR to fix it: https://github.com/AcademySoftwareFoundation/MaterialX/pull/1291
