### ISSUE TITLE
Minimal example of a custom node that references an OSL shader for implementation?

### ISSUE THREAD

**Issue by joaovbs96** [AcademySoftwareFoundation/MaterialX#1306]
Hi! I'm having some trouble trying to come up with a minimal example of a .mtlx file that could take some parameters or information from an OSL shader. I've read the spec as well as other guides, but I keep missing something basic, I think.

Is there, or could someone provide, an example of a fully functional, yet minimal, MaterialX file that takes a very minimal OSL shader, that for example just returns a static color, and assigns it to some property of a Material?

An additional question, just to clarify, is: does the MaterialX viewer support such shader file references for node implementations? Or would I run into issues there?

Apologies in advance if this is not the correct place for this question!

**Comment by joaovbs96** [comment]
Thank you so much! This helps a lot.

Since we got to the topic, is OSL rendering support to the viewer planned eventually?

**Comment by niklasharrysson** [comment]
Eventually, maybe, but not for the near term.

To validate OSL shaders, in our test suite, we currently use the `testrender` application that is part of the OSL distribution. It's a very simplistic path tracer with limited support to geometry loading and no interactive rendering. On the OSL side there has been talk of extending `testrender` to be more generally useful, for example to support loading arbitrary meshes etc. When this development gets further we may consider adding `testrender` as another backend renderer to MaterialXView to show path traced results there in addition to the OpenGL rendering.

There is already support for generating OSL shaders in the Viewer though. If you load in a material and then press 'o' (for OSL) an OSL shader will be generated and saved to a file. You can then render with this shader in `testrender` or any another OSL renderer.

**Comment by jstone-lucasfilm** [comment]
Thanks to @joaovbs96 for posting this question, as well as to @niklasharrysson for the thoughtful answers.  My sense is that these examples address the question well, so I'll go ahead and mark this as resolved.
