### ISSUE TITLE
Add MinGW support for building

### ISSUE THREAD

**Issue by wusikijeronii** [AcademySoftwareFoundation/MaterialX#1337]
Hello.
Today I wanted to try this library, and I faced some problems when I built it. So I tested it using Git Bash (by the MSYS2 backend).
I tried it:
1. GCC on the MSVS environment C runtime
2. Clang on the UCRT environment, C runtime

Errors:
```shell
D:/apps/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libMaterialXRenderGlsl.a(GlslRenderer.cpp.obj):GlslRenderer.c:(.text+0x31c): undefined reference to `MaterialX_v1_38_7::SimpleWindow::initialize(char const*, unsigned int, unsigned int, void*)'
D:/apps/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libMaterialXRenderGlsl.a(GlslRenderer.cpp.obj):GlslRenderer.c:(.text$_ZN17MaterialX_v1_38_712SimpleWindow6createEv[_ZN17MaterialX_v1_38_712SimpleWindow6createEv]+0x27): undefined reference to `MaterialX_v1_38_7::SimpleWindow::SimpleWindow()'
D:/apps/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libMaterialXRenderGlsl.a(GLContext.cpp.obj):GLContext.cpp:(.text+0x127): undefined reference to `__imp_wglCreateContext'
D:/apps/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libMaterialXRenderGlsl.a(GLContext.cpp.obj):GLContext.cpp:(.text+0x15b): undefined reference to `__imp_wglShareLists'
D:/apps/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libMaterialXRenderGlsl.a(GLContext.cpp.obj):GLContext.cpp:(.text+0x186): undefined reference to `__imp_wglMakeCurrent'
D:/apps/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libMaterialXRenderGlsl.a(GLContext.cpp.obj):GLContext.cpp:(.text+0x21a): undefined reference to `__imp_wglDeleteContext'
D:/apps/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libMaterialXRenderGlsl.a(GLContext.cpp.obj):GLContext.cpp:(.text+0x2d4): undefined reference to `__imp_wglMakeCurrent'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

I found the reason for this issue. source\MaterialXRenderGlsl\CMakeLists.txt:
```cmake
if(MSVC)
    target_link_libraries(
        MaterialXRenderGlsl
        ${COMMON_LIBRARIES}
        Opengl32)
elseif(APPLE)
    target_link_libraries(
        MaterialXRenderGlsl
        ${COMMON_LIBRARIES}
        ${OPENGL_LIBRARIES}
        "-framework Foundation"
        "-framework Cocoa"
        "-framework Metal")
elseif(UNIX)
    target_link_libraries(
        MaterialXRenderGlsl
        ${COMMON_LIBRARIES}
        ${OPENGL_LIBRARIES}
        ${X11_LIBRARIES}
        ${X11_Xt_LIB})
endif()
```

The if condition in my case is always false:
1. I don't use the MSVC compiler. I use Clang or GCC.
2. My OS is not MacOS. It is Windows.
3. Windows is not Unix. But I tried to build the library right from MSYS2, and then I got another errors because Windows doesn't have the X11 server.

Modifying CmakeLists.txt here works for me. But I think you, as the library owner, have to modify this condition too.

**Comment by jstone-lucasfilm** [comment]
Good catch, @wusikijeronii, and this sounds like a worthwhile change to our CMake configuration.  Since you've already tested and verified a potential fix, would you have the bandwidth to write this up as a pull request to the MaterialX project?

**Comment by wusikijeronii** [comment]
@jstone-lucasfilm I've created the pull request. Congratulations to me on my first pull request. But I don't have the CLA authorization. I tried to create the sign, but even when I filled out all the fields, these fields were still red. I really don't want to figure DocuSign out. But the modification is only a few lines in Cmake. Maybe it's better that you make this request?

**Comment by jstone-lucasfilm** [comment]
@wusikijeronii Let's see if we can move that CLA through, since the Linux Foundation is really good about providing support on this system, and ideally we want the CLA process to be seamless for new contributors.  I'll ping the new PR that you're written up.

**Comment by jstone-lucasfilm** [comment]
It looks like the CLA has gone through, thanks for writing this proposal up!

**Comment by wusikijeronii** [comment]
After 5 attempts and pressing the next/fill buttons, I found the finish button. The fields were still red! But I pressed and I did it all right. Super comfortable US sites :(
