### ISSUE TITLE
Downstream traversal does not traverse through nodegraphs / interface

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1348]
### The issue

`getMatchingPorts()` currently only checks the `node` attribute on a port to compare against a given upstream name. 
Thus connections specified using `nodegraph` or `interfacename` attributes are missed.

### Sample workflows affected:
* A workflow example is trying to find the downstream renderable for a given node in the node editor.
It will always stop early and never find a downstream shader node connected to a nodegraph if starting from
within a node in the nodegraph. As a number of example graphs use this type of configuration  it's quite easy to not switch
to the correct material when selecting nodes inside a nodegraph. (e.g. the chess set graphs don't provide correct switching)

* I am unsure if this make some cases for definition flattening fail but it is possible since connections can be missed.
`nodegraph`->`nodegraph` and `node`->`nodegraph` connections are candidates for issues with flattening. 

* Any type of "dirty propagation" scheme which depends on updating downstream nodes will stop early.

### Proposed Fix
* The fix appears to be to simply update the "port name map" cache to include the appropriate check for attributes which are not `node`. A proposed "better" long term solution is to remove the variance in connection names and only use one name.
* A secondary fix which can be deferred for now would be to modify the cache to keep paths instead of names as names are only unique within the context of the parent so an it seems that incorrect results can occur with 2 nodes named the same within a different context (e.g. one inside a nodegraph and one outside)

### Test 
* This is a sample test with marble graph, starting with `noise`.
* It will halt before the nodegraph output, when it should reach through to the surfaceshader and material nodes.

```python
def getDownstreamPorts(nodeName):
    downstreamPorts = []
    for port in doc.getMatchingPorts(nodeName):
        downstreamPorts.append(port)
    return downstreamPorts

def getDownstreamNodes(node, foundPorts, foundNodes, renderablePort):
    testPaths = set()
    testPaths.add(node.getNamePath())

    while testPaths:
        nextPaths = set()
        for path in testPaths:
            testNode = doc.getDescendant(path)
            ports = getDownstreamPorts(testNode.getName())
            for port in ports:
                downNode = port.getParent()
                downNodePath = downNode.getNamePath()
                if downNode and downNodePath not in nextPaths: #and downNode.isA(mx.Node):
                    foundPorts.append(port.getNamePath())
                    if port.isA(mx.Output):
                        renderablePort.append(port.getNamePath())
                    nodedef = downNode.getNodeDef()
                    if nodedef:
                        nodetype = nodedef.getType()
                        print('Check node category:', nodetype)
                        if nodetype in ['material', 'surfaceshader', 'volumeshader']:
                            print('Renderable node category:', nodetype)
                            renderablePort.append(port.getNamePath())
                    foundNodes.append(downNode.getNamePath())
                    nextPaths.add(downNodePath)

        testPaths = nextPaths

nodegraph = doc.getChild('NG_marble1')
node = nodegraph.getChild('noise')

foundPorts = []
foundNodes = []
renderablePort = []
getDownstreamNodes(node, foundPorts, foundNodes, renderablePort)
print('Starting node: ', node.getNamePath())
print('Downstream ports:', ', '.join(foundPorts))
print('Downstream nodes:', ', '.join(foundNodes))
print('Renderable ports:', ', '.join(renderablePort))
```

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @kwokcb, and I'll mark this as resolved with the merge of #1349.
