### ISSUE TITLE
Add implementation of blackbody node for all targets

### ISSUE THREAD

**Issue by niklasharrysson** [AcademySoftwareFoundation/MaterialX#1356]
MDL is the only target that has an implementation for the <blackbody> node. It should be implemented for GLSL and OSL as well.

**Comment by nicolassavva-autodesk** [comment]
We are preparing an implementation, based on a cubic spline fit (https://en.wikipedia.org/wiki/Planckian_locus#Approximation)
and will open a PR addressing this shortly: 
https://github.com/autodesk-forks/MaterialX/compare/adsk_contrib/dev...autodesk-forks:MaterialX:pbr_blackbody?expand=1

**Comment by ashwinbhat** [comment]
@niklasharrysson (fyi)

**Comment by jstone-lucasfilm** [comment]
This is now addressed in #1367, thanks @nicolassavva-autodesk and @niklasharrysson!
