### ISSUE TITLE
Feature Request: Incident vector and "camera" space

### ISSUE THREAD

**Issue by AlexeySmolenchuk** [AcademySoftwareFoundation/MaterialX#1358]
Currently, there is no way to get an Incident vector in MaterialX shading network, but this variable is crucial for many shading effects.

Another important option would be to have a "camera" as a valid space for MaterialXTransform* nodes.

**Comment by jstone-lucasfilm** [comment]
This is a good suggestion, @AlexeySmolenchuk, and I'll note that we've discussed the inclusion of a `viewdirection` node as part of an `nprlib` data library in MaterialX:

https://academysoftwarefdn.slack.com/archives/C0230LWBE2X/p1683661456425219

There's a bit of additional history in that thread, as to why `viewdirection` doesn't currently exist as a node, and there's a great deal of interest in including this node in MaterialX 1.39.

**Comment by jstone-lucasfilm** [comment]
See #1631 for an initial implementation of this feature.

**Comment by jstone-lucasfilm** [comment]
Thanks for writing this up, @AlexeySmolenchuk, and this should now be resolved with the merge of #1631.
