### ISSUE TITLE
Integer support for the basic Math nodes.

### ISSUE THREAD

**Issue by crydalch** [AcademySoftwareFoundation/MaterialX#1364]
It would be good to take a pass at improving the integer support in MaterialX's math nodes. Having these low-level building-blocks would improve the types of nodegraphs that can be expressed.

**Node**|**Input**|**Output**
:-----:|:-----:|:-----:
Add|integer, integer|integer
Add|integer, float|integer
Subtract|integer, integer|integer
Subtract|integer, float|integer
Multiply|integer, integer|integer
Multiply|Integer, float|integer
Divide|integer, integer|integer
Divide|integer, float|integer
Min|integer, integer|integer
Max|integer, integer|integer

I'm not sure if there are other options necessary. Or if we need to do things like Vector (I) signatures...

**Comment by dbsmythe** [comment]
I would disagree with having e.g. an "Add" with integer and float inputs, and certainly with having that combination produce an integer output.  Instead, I would suggest we only have same-type inputs and outputs for the nodes themselves, and refine the "auto convert" logic to insert conversion nodes (int to float "convert", or "floor(float) with int output") when someone wants to connect a different type to an input, similar in concept to what we do with swizzle/extract or colorspace-convert on input.

Not sure about how useful integer vector types would be- do you have any use cases in mind?

**Comment by crydalch** [comment]
Thanks @dbsmythe - that all makes sense. The integer-vector types was more about vec3 * int cases - and only for the sake of completeness. If the math nodes only supported integer inputs and outputs, that's perfectly fine by me. As you pointed out, (in the future) integer-aware `floor` and `ceil`, along with future `round` can take care of float-to-int cases.

**Comment by jstone-lucasfilm** [comment]
Linking this issue to the recent work from @ld-kerley on #1777 and #1786.

**Comment by jstone-lucasfilm** [comment]
Thanks for this original proposal, @crydalch, and I think that we can close this out, as a good fraction of this work has been implemented in MaterialX 1.39.  Feel free to post additional ideas for integer math improvements in new GitHub Issues.
