### ISSUE TITLE
Add a Round node

### ISSUE THREAD

**Issue by crydalch** [AcademySoftwareFoundation/MaterialX#1365]
The integer discussions have raised the usefulness of having a `round` node. This thread is for the questions and discussions of features. The current thinking is that `round` would be implemented as a nodegraph, after integer support is added to `ceil` and `floor` (see PR #1362).

**Comment by jstone-lucasfilm** [comment]
Adding a link to PR #1661 which addresses this issue.

**Comment by ld-kerley** [comment]
Actually new PR submitted against `main` - #1678

**Comment by jstone-lucasfilm** [comment]
Thanks to @crydalch for this original suggestion, and to @ld-kerley for the implementation!
