### ISSUE TITLE
MaterialXViewer: input values aren't initialized properly

### ISSUE THREAD

**Issue by amsXYZ** [AcademySoftwareFoundation/MaterialX#1383]
Hi there!

I've noticed that, whenever I create a `.mtlx` file that uses `input` elements to expose material properties, these inputs don't get initialised properly with their 'value' attribute in **MaterialXViewer**. They do instead get initialised with the **default** value of the attribute they're connected to.

This is creating some issues in our image-testing setup, since we do read these 'input' values from the '.mtlx' file, and it's giving us completely different rendering results to what **MaterialXViewer** renders out-of-the-box.

Here's an example of the issue:

```
<?xml version="1.0"?>
<materialx version="1.38" colorspace="lin_rec709">
  <surface name="surface" type="surfaceshader" xpos="14.688406" ypos="-0.629310">
    <input name="bsdf" type="BSDF" nodename="dielectric_bsdf" />
  </surface>
  <surfacematerial name="surfacematerial" type="material" xpos="16.043478" ypos="-0.698276">
    <input name="surfaceshader" type="surfaceshader" nodename="surface" />
  </surfacematerial>
  <input name="input_color3" type="color3" value="1, 0, 0" xpos="10.442029" ypos="-2.318965" />
  <input name="input_vector2" type="vector2" value="0.05, 0.05" xpos="10.442029" ypos="-0.103448" />
  <dielectric_bsdf name="dielectric_bsdf" type="BSDF" xpos="12.659420" ypos="-1.905172">
    <input name="tint" type="color3" interfacename="input_color3" />
    <input name="ior" type="float" interfacename="input_float" />
    <input name="roughness" type="vector2" interfacename="input_vector2" />
    <input name="scatter_mode" type="string" value="T" />
  </dielectric_bsdf>
  <input name="input_float" type="float" value="1.5" xpos="10.442029" ypos="-1.215517" />
</materialx>
```

We expect the above material to render a red-transmissive `dielectric_bsdf` response (see how the `input_color3` is set to a value of `1, 0, 0`), but instead get this result when rendering it in **MaterialXViewer**:

<img width="1392" alt="image" src="https://github.com/AcademySoftwareFoundation/MaterialX/assets/6959189/b41cfe05-1cf4-41c4-8533-d59f5d133de3">

If we manually set the color to red, we get the expected result rendered:

<img width="1392" alt="image" src="https://github.com/AcademySoftwareFoundation/MaterialX/assets/6959189/2b62c7a6-59c8-47af-afe2-920c21ee0935">

This also happens in the preview window of the **MaterialXGraphEditor**.

Just to clarify, this is not an issue when using a `constant` element or using inlined values directly on the nodes. But we can't go with these options, as we want users to be able to modify these values without manually modifying the `.mtlx` file.

**Comment by amsXYZ** [comment]
@kwokcb Where is it in the spec that root `inputs` aren't supported? Is there any good reason for this? 🤔 I haven't seen that, but I might be wrong.

And looking at your graph, I'm confused at the fact that the root `nodegraph` inputs are exposed as user-facing material properties. What's the criteria here? Any nodegraph `input` using an `interfacename` should be exposed? Is this explained in the spec anywhere? What about the inputs of a `nodegraph` nested inside another `nodegraph`?

All of this "exposed properties" topic is a bit vague in the spec, and not sure why the solution is not "treat root inputs as exposed properties". It makes sense logically (as they're inputs to the top-most level, so they should be user-facing) and work pretty well in our implementation 🤔

**Comment by jstone-lucasfilm** [comment]
@amsXYZ @kwokcb To my mind, it's just an oversight in the MaterialX codebase that `input` elements at the root scope of a document aren't respected in shader generation.  We should view this as a bug to be fixed, and not intentional behavior for artists and developers to work around.

**Comment by kwokcb** [comment]
Hmm. my bad then. I think this impression also came from the fact that there is no mentioned of allowing for `interfacename` connections outside of nodegraphs. Maybe the spec should be updated to mention these connections are possible at the document level as well ?

BTW, what is the use of adding these additional inputs (and connections) as opposed to just directly editing values on the nodes ? There is no real notion of "hiding" inputs at the document level.

**Comment by stramit** [comment]
@kwokcb  This becomes more important when looking at things from a real-time perspective. When designing a real time material it's useful to have certain properties be overridable in the runtime or bound to runtime values (we do this a lot with things like color parameters, uv tiling, lots of user specific things). 

Each of these exposed properties generally get put into a constant buffer and you want to keep these as small and concise as possible for performance and memory reasons, so exposing everything isn't a great idea.

Essentially you want to design an interface to the material (i.e inputs) for the things that can be modified by the realtime engine. This also has the advantage of having a well defined intentional set of modifiable input parameters. Normally node values that are not exposed this way get inlined into the shader code directly instead of being modifiable by the runtime.

**Comment by kwokcb** [comment]
Hi @stramit,
The additional clarification is very useful. 

So for posterity, keeping a note that we can follow the same semantic logic for graphs at any level for consistency: i.e.
1. Without code generation, `interfacename` still implies public interface building.
2. For built in code generation use the same logic option to allow for interfaces to be "public" vs "private" uniform / blocks 

I'm not sure if we need any further differentiation of a input interface on a top-level nodegraph vs one on a top-level node, 
wherein you could theoretically have a top level interface input attached to an interface input on a nodegraph.

Will leave a ping with @niklasharrysson so he's in the loop, as I'm also not sure what this means (if anything for shading languages like OSL and MDL).

**Comment by jstone-lucasfilm** [comment]
Thanks to @kwokcb for addressing this in #1453, and I've verified that the example material above renders with red transmission in the main branch.
