### ISSUE TITLE
Failing to build materialx 1.38.7 on windows using VS2017

### ISSUE THREAD

**Issue by tallytalwar** [AcademySoftwareFoundation/MaterialX#1401]
Hello

While doing a USD build on windows with VS2017 using the [build script](https://github.com/PixarAnimationStudios/OpenUSD/blob/release/build_scripts/build_usd.py), materialx failed to build owing to missing _cctype_ header in metal shader gen code base which uses [std::isspace](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/source/MaterialXGenMsl/MslShaderGenerator.cpp#L335).

We are modifying the USD build script by applying a patch in order to unblock us.

Thanks

**Comment by jstone-lucasfilm** [comment]
Thanks for this catch, @tallytalwar!  Would your team have the bandwidth to propose a pull request, or would you prefer that we tackle this on our side?  Either way, it sounds like a worthwhile fix to include in the upcoming 1.38.8 release.

**Comment by tallytalwar** [comment]
Thanks @jstone-lucasfilm. @klucknav has a CLA already, so she submitted a PR for this.
