### ISSUE TITLE
Handle 1x1 textures in GLSL Image Nodes

### ISSUE THREAD

**Issue by klucknav** [AcademySoftwareFoundation/MaterialX#1438]
The glsl shaders generated for image nodes all start with a check that the width is strickly greater than 1. So every texture that is 1xH will get the defaultval, instead of the texture color. Since it is a common pattern to use 1x1 textures, it would be prefable if the default value was not used for the 1x1 texture case.

**Comment by kwokcb** [comment]
I think the easiest way to fix this is to do like OSL, and pass over a flag to indicate if the texture is provided. Then there are no hardware limitation to testing for this condition, no additional dummy textures required, and default color changes are not resource binding Nora toploical change (I.e no new shadergen is required).The renderer will need to set this uniform. A suitable flag name will need to be injected as shader function arg, but this can be generated and published as a known notation.

 Does this sound acceptable?

**Comment by jstone-lucasfilm** [comment]
Thanks for posting this issue @klucknav, and now that our teams have returned from the SIGGRAPH conference, I'd like to make this a high priority to resolve in the next few weeks.

@kwokcb Although that's the simplest solution, the reason I'd recommend against it is the need for a second shader uniform for every `image` node in a MaterialX graph, in addition to the dynamic branch for each `image` node that currently exists.  My recommendation would be to go in the _opposite_ direction, making the renderer responsible for replacing missing images with 1x1 textures, and removing the dynamic branch that currently exists in GLSL/MSL shader code.  This way, we could resolve the issue that @klucknav notes and improve real-time render performance at the same time.

**Comment by kwokcb** [comment]
Very good points on dynamic branching and the extra uniform. 

To check, we can remove the  the "default color" argument from the shader so advantage of 1 less uniform. However, "default color"  is now up to the renderer now to create textures from a color. 

BTW: The reasoning for the flag input (which in OSL is not an additional uniform since it's a struct) is to allow for not requiring any texture uniform to be emitted at all as no texture is required to be bound. Also to allow for "default color" to change dynamically without a texture (re)bind.

**Comment by kwokcb** [comment]
To "discover" what is the default, suggest to add a `defaultinput` attribute value on the output. This would reference to the `default color` input so that a renderer can discover what color to use. This would be for `<image>, <tileimaged> and <triplanarmapping>` nodes I think.

**Comment by jstone-lucasfilm** [comment]
Here's an initial proposal to resolve this issue, and if this looks like a good step forward, perhaps we can include this in the upcoming 1.38.8 release:

https://github.com/AcademySoftwareFoundation/MaterialX/pull/1452

**Comment by jstone-lucasfilm** [comment]
@klucknav The proposal in #1452 has been merged to main, and let us know how this works out in Hydra/Storm!
