### ISSUE TITLE
Test Suite results for pbrlib/bsdf/wedge_conductor are not consistent

### ISSUE THREAD

**Issue by krohmerNV** [AcademySoftwareFoundation/MaterialX#1441]
The wedge_conductor material shown in the image has an anisotropy of 0.0. Yet OSL and GLSL produce something anisotrop.

https://github.com/AcademySoftwareFoundation/MaterialX/blob/c34a1066bb194d36174454b3b763a6d68bc8480d/resources/Materials/TestSuite/pbrlib/bsdf/wedge_conductor.mtlx#L6

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/42233792/fff48891-07ee-4a75-abb5-116416333dea)

**Comment by kwokcb** [comment]
As a sanity test I tried this out in `MaterialXView` and looks the same as MDL. Running a "wedge" (`w`) on `anisotropy` also seems fine (for GLSL) so this seems good.
![w](https://github.com/AcademySoftwareFoundation/MaterialX/assets/49369885/31c49eb3-cc26-42a6-9414-70aa4079e235)

I see the "issue" now. As part of the test suite we run a wedge render as part of the options. It seems that MDL is using this option for which the last anisotropy value is 1.0. Hence GLSL and OSL are correct but MDL is not rendering the with 1.0 but instead 1.0.

Side notes:
1. OSL wedge render seems to not work for roughness and aniostropy (all images look the same)
2. Wedge renders are stored as bmp files (not sure why) and don't show up in the compare util.
( I think wedge rendering in the test suite needs to looking into ... )

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @krohmerNV, and I believe this issue is now addressed in #1717.
