### ISSUE TITLE
LookupError: Could not find a nodedef for node 'file1'

### ISSUE THREAD

**Issue by guxiangmyhome** [AcademySoftwareFoundation/MaterialX#1442]
MaterialX/python/Scripts/generateshader.py

**Comment by guxiangmyhome** [comment]
main([r'C:\wubi\wubi_test\maya\materialx_test\psphere_mx.mtlx', '--path', r'C:\wubi\wubi_dev\MaterialX', '--library', r'C:\wubi\wubi_dev\MaterialX\libraries\stdlib'])
main([r'C:\wubi\wubi_dev\MaterialX\resources\Materials\Examples\StandardSurface\standard_surface_carpaint.mtlx', '--path', r'C:\wubi\wubi_dev\MaterialX', '--library', r'C:\wubi\wubi_dev\MaterialX\libraries\stdlib'])
standard_surface_carpaint.mtlx this example mtlx file works file

**Comment by guxiangmyhome** [comment]
main([r'C:\wubi\wubi_test\maya\materialx_test\psphere_mx.mtlx', '--path', r'C:\wubi\wubi_dev\MaterialX', '--library', r'C:\wubi\wubi_dev\MaterialX\libraries\stdlib'])
Traceback (most recent call last):
  File "C:\wubi\wubi_210\wubi_dev\210_maya\maya_core_210\materialx\generate_shader.py", line 218, in <module>
    main([r'C:\wubi\wubi_test\maya\materialx_test\psphere_mx.mtlx', '--path', r'C:\wubi\wubi_dev\MaterialX', '--library', r'C:\wubi\wubi_dev\MaterialX\libraries\stdlib'])
  File "C:\wubi\wubi_210\wubi_dev\210_maya\maya_core_210\materialx\generate_shader.py", line 171, in main
    shader = shader_gen.generate(node_name, node, context)
LookupError: Could not find a nodedef for node 'file1'
when i use my custom mtlx, have this error
the custom mtlx, is my test scene, just created a sphere, assign a arnold standard surface, then export use arnold

**Comment by kwokcb** [comment]
Hi @guxiangmyhome ,

Without knowing what is in your your mtlx file it is very hard to tell what's going on.

As a guess:
1. You are using Maya specific nodes and have not loaded in those definitions.
2. You are using Arnold nodes which cannot be recognized outside the Arnold ecosystem, in which case this will never work.

My guess is 1, but as said there is insufficient information. In this case
Please run `generatehader --help` to get the args for specify additional library paths:
```
  --path PATHS [PATHS ...]
                        An additional absolute search path location (e.g. "/projects/MaterialX")
  --library LIBRARIES [LIBRARIES ...]
                        An additional relative path to a custom data library folder (e.g. "libraries/custom")
```
and use the appropriate path to the Maya definitions.

**Comment by guxiangmyhome** [comment]
how can i find the Maya definitions path ? maya library path ? 
C:\Program Files\Autodesk\Maya2022   i searched here with keyword library, nothing return.

**Comment by guxiangmyhome** [comment]
<?xml version="1.0"?>
<materialx version="1.38">
  <surfacematerial name="aiStandardSurface1SG" type="material">
    <input name="surfaceshader" type="surfaceshader" nodename="aiStandardSurface1" />
  </surfacematerial>
  <standard_surface name="aiStandardSurface1" type="closure">
    <input name="base_color" type="color3" nodegraph="NG_file1" output="out" />
  </standard_surface>
  <nodegraph name="NG_file1">
    <image name="file1" type="color4">
      <input name="filename" type="string" value="C:/wubi/wubi_test/maya/tex/HeartClouds.jpg" />
      <input name="color_space" type="string" value="sRGB" />
      <input name="ignore_missing_textures" type="boolean" value="true" />
      <input name="missing_texture_color" type="color4" value="0.5, 0.5, 0.5, 0" />
    </image>
    <output name="out" type="color3" nodename="file1" />
  </nodegraph>
</materialx>
this is my custom mtlx file content, can you help me check what the issue is ? thanks !

**Comment by guxiangmyhome** [comment]
`<?xml version="1.0"?>
<materialx version="1.38">
  <surfacematerial name="aiStandardSurface1SG" type="material">
    <input name="surfaceshader" type="surfaceshader" nodename="aiStandardSurface1" />
  </surfacematerial>
  <standard_surface name="aiStandardSurface1" type="closure">
    <input name="base_color" type="color3" nodegraph="NG_file1" output="out" />
  </standard_surface>
  <nodegraph name="NG_file1">
    <image name="file1" type="color4">
      <input name="filename" type="string" value="C:/wubi/wubi_test/maya/tex/HeartClouds.jpg" />
      <input name="color_space" type="string" value="sRGB" />
      <input name="ignore_missing_textures" type="boolean" value="true" />
      <input name="missing_texture_color" type="color4" value="0.5, 0.5, 0.5, 0" />
    </image>
    <output name="out" type="color3" nodename="file1" />
  </nodegraph>
</materialx>
`

**Comment by guxiangmyhome** [comment]
i'm testing export maya material to ue5, include arnold material, redshift material,
is materialx the best solution ? for now, i can only export arnold material to mtlx file, 
is there any python api i can use to export redshift material to mtlx file ?
import mtlx to ue5 is another issue, for now, i cannot import arnold mtlx file into ue, always error

**Comment by guxiangmyhome** [comment]
maya arnold has function to export shader to materialx, 
for now rs not support materialx, is there any python api i can use to export redshift material to mtlx file ?
inside ue5, for now import mtlx always error,  is there any python api i can use to import mtlx file ?

**Comment by guxiangmyhome** [comment]
MaterialX/resources/Materials/Examples/StandardSurface/standard_surface_chess_set.mtlx
i tried import this example file into ue5, it works. 
so how can i export a correct mtlx file ? i tried aistandardsurface, also tried maya standardsurface, all not working.

**Comment by guxiangmyhome** [comment]
is there any python api i can use to export a correct mtlx file that ue5 can recognize ?

**Comment by kwokcb** [comment]
Hi @guxiangmyhome 
I think there are too many questions that don't really belong in an issue :) 

Just for the issue, it was the second guess. 
You are using the "custom" `Arnold` notation for MaterialX which **only** Arnold understands. 
Suggest you reach out to Maya / Arnold / UE folks as for support. For Maya you might want to look into `LookdevX`

Perhaps you can try the  ASWF MaterialX Slack channel as representatives from each product should be there. (or whatever the correct forums are for each product.)

I would like to close this out as something that is not a "core" issue.

**Comment by guxiangmyhome** [comment]
@kwokcb thank you very much !
