### ISSUE TITLE
Compilation freezes on Artix Linux

### ISSUE THREAD

**Issue by longboarder241** [AcademySoftwareFoundation/MaterialX#1443]
So I don't know if its my lack of ram but it seems that when compiling MaterialX on artix locks up at 64%, even running under just a tty interface.  I wouldn't expect this with 16gb but is anyone else experiencing this?  Is there a way to limit its ram utilization if its just a hardware issue?

**Comment by jstone-lucasfilm** [comment]
@longboarder241 I haven't had the opportunity to build MaterialX on artix, but so far I haven't encountered this issue with other Linux distributions (e.g. Ubuntu, RHEL).  Let us know if you have any insights into what might be going awry, and we're open to adding build options that extend MaterialX support to new environments.

**Comment by jstone-lucasfilm** [comment]
@longboarder241 I haven't had the opportunity to build MaterialX on artix, but so far I haven't encountered this issue with other Linux distributions (e.g. Ubuntu Linux in our GitHub Actions suite).

Let us know if you have any insights into what might be going awry, and we're open to adding build options that extend MaterialX support to new environments.

**Comment by jstone-lucasfilm** [comment]
Let us know if you have additional thoughts, on this, @longboarder241, and for now I'll close out this issue.
