### ISSUE TITLE
Graph Editor: compilation time for simple node graph

### ISSUE THREAD

**Issue by marwie** [AcademySoftwareFoundation/MaterialX#1455]
Hello,

I noticed that opening /compiling this simple graph takes significantly longer than e.g. the marble material example or other materials in the examples. It's also just a surfacematerial with standard_surface and a few nodes. I'm wondering if this is expected and caused by the nodes being used?

```xml
<?xml version="1.0"?>
<materialx name="" version="1.38" >
	<nodegraph name="needle_shadergraph" >
		<!-- MyColor -->
		<input name="_MyColor" type="color4" value="0.8113207, 0.5396048, 0.5396048, 1.0" />
		<constant name="const__MyColor" type="color4" >
			<input name="value" type="color4" interfacename="_MyColor" />
		</constant>
		<convert name="convert_to_color3" type="color3" >
			<input name="in" type="color4" nodename="const__MyColor" />
		</convert>
		<output name="out" type="color3" nodename="convert_to_color3" />
		<convert name="convert_to_color3_1" type="color3" >
			<input name="in" type="float" value="5.0" />
		</convert>
		<multiply name="mult" type="color3" >
			<input name="in1" type="color3" nodename="convert_to_color3" />
			<input name="in2" type="color3" nodename="convert_to_color3_1" />
		</multiply>
		<output name="out_1" type="color3" nodename="mult" />
	</nodegraph>
	<standard_surface name="needle_standard_surface" type="surfaceshader" >
		<!-- Base Color(3) -->
		<input name="base_color" type="color3" nodegraph="needle_shadergraph" output="out" />
		<!-- Emission(3) -->
		<input name="emission_color" type="color3" nodegraph="needle_shadergraph" output="out_1" />
		<!-- Metallic(1) -->
		<input name="metalness" type="float" value="1.0" />
	</standard_surface>
	<surfacematerial name="Default" type="material" >
		<input name="surfaceshader" type="surfaceshader" nodename="needle_standard_surface" />
	</surfacematerial>
</materialx>

```

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/4a771d2a-b2a0-44db-b878-c9f97c14d7ae

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @marwie, though I wasn't able to repro the issue in my local Windows build.

I wonder if the issue is related to driver-level shader caching, where the requested shader wasn't present in the cache when you tested this on your machine?

I'll leave this issue open for now, to see if it resonates with other members of the community, but in my local tests I'm seeing similar shader compile times for your example material and other standard examples such as marble and copper.

**Comment by kwokcb** [comment]
I was also not able to detect any noticeable slowdown. My GPU pegs at close to 100% sometimes which does cause hiccups. Perhaps this could be a cause. I went in and lowers the sample env count and it makes it less lag. 
( @jstone-lucasfilm: Perhaps its worth adding in a fidelity option as with the Viewer ? )

**Comment by marwie** [comment]
I just tried this again with the latest version and it doesnt seem to happen anymore
