### ISSUE TITLE
Graph Editor: convert color4 to color3 doesnt work / connection is refused

### ISSUE THREAD

**Issue by marwie** [AcademySoftwareFoundation/MaterialX#1459]
I have a vector4 that I want to modify and use as a color3 in the end but something doesnt seem to work and the material stays black / the connection doesn't seem to be made. No messages in the console

Here are the materials: [add color.zip](https://github.com/AcademySoftwareFoundation/MaterialX/files/12378549/add.color.zip)

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/13dec6cd-863a-480b-9697-4ddf96cdf740

In the end the convert color4 to color3 node seems to have broken as well

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/33b30af0-f7e6-4fb9-9d88-8078139851be)

**Comment by kwokcb** [comment]
@marwie, @jstone-lucasfilm 
This should also work now with the downstream logic change. I tried both add_color.mtlx and add_color2.mtlx and seems to update okay.

**Comment by jstone-lucasfilm** [comment]
Thanks for the update, @kwokcb!
