### ISSUE TITLE
Graph Editor: crash when pasting nodes from previously opened graph

### ISSUE THREAD

**Issue by marwie** [AcademySoftwareFoundation/MaterialX#1461]
Hi, the editor crashes when I paste nodes that I copied from a previously opened graph

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/54ffd53c-dffd-43c5-877b-8ad0a89a7fd7

copy paste of a single node of a saved graph works:

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/9d094c9f-c8fc-4a89-b0fa-c5ceb943d6ce

copy paste of multiple nodes for a saved graph crashes:

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/6a9d11e0-c0da-457b-bbd7-78c4d9fa71ef

**Comment by jstone-lucasfilm** [comment]
Thanks for this great report, @marwie, and I've proposed a fix for the issue in #1467.

**Comment by jstone-lucasfilm** [comment]
The fix has now been merged, and let us know how things look in a new build.
