### ISSUE TITLE
Structs used in final generated OSL shaders, makes it hard for DCC UI's to cope

### ISSUE THREAD

**Issue by ZapAndersson** [AcademySoftwareFoundation/MaterialX#1463]
The code generation for OSL, when used to generate a final shader, it uses a struct parameter:

```
...
struct textureresource { string filename; string colorspace; };
...
shader image_color3
[[
    string mtlx_category = "image",
    string mtlx_name = "image_color3"
]]
(
    textureresource  file = {"", ""}
    [[
        string widget = "filename"
    ]],
    string layer = "",
    color default1 = color(0, 0, 0),
    vector2 texcoord = {u,v},
    string uaddressmode = "periodic",
    string vaddressmode = "periodic",
    string filtertype = "linear",
    string framerange = "",
    int frameoffset = 0
    [[
        string widget = "number"
    ]],
    string frameendaction = "constant",
    output color out = color(0.0)
)
{
    color image_color3_out = color(0.0);
    mx_image_color3(file, layer, default1, texcoord, uaddressmode, vaddressmode, filtertype, framerange, frameoffset, frameendaction, image_color3_out);
    out = image_color3_out;
}
```

This causes issues, not all DCC's can handle struct inputs (I've been told Katana can not), but even for those that do, the metadata gets applied to the whole parameter, not individual struct items. So this means that both file.filename and file.colorspace ands up being treated as "filename" widgets and get a file picker, which is suboptimal for sure.

Talking to @niklasharrysson he said it would be fairly easy to remove the struct from the generated code, so it just shows up as regular parameters.

I propose to do just that, and instead have a convention for parameters, so it would end up as

string file [[ string widget="filename" ]],
string file_ColorSpace [[ string widget="colorspace" ]],

...or something similar instead.

/Z

**Comment by niklasharrysson** [comment]
@ZapAndersson Thanks for creating the issue.

I have made a fix to this in my fork that you can try. The branch is here: https://github.com/niklasharrysson/MaterialX/tree/osl_filename_params

Let me know if it's not working as expected.

**Comment by ZapAndersson** [comment]
Thanks, we will take a look.

In the meantime we made a python hack workaround, and in making it, I noticed the color space never gets put in the OSL texture(). I know this is not implemented yet on the OSL side (just talked to @lgritz about that the other day) but it should be safe to put it in as an optional parameter already.

/Z

**Comment by ZapAndersson** [comment]
@niklasharrysson I tested your branch, and while this solves the issue with the parameters, the color space ends up never being used, basically we need

![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/102356572/2805693c-ba8b-416b-b344-cbf40689046d)

Now I know the optional parameter "colorspace" is not implemented in mainline OSL yet, but it's been discussed, and since it is indeed an optional parameter, putting it in "before it exists in mainline" should be safe. Right @lgritz ?

Also we have just invented the new widget type "colorspace" which is not defined in mainline yet, which we should. I'll bring this up on the next OSL TSC

**Comment by lgritz** [comment]
Yeah, we need to add that.

**Comment by kwokcb** [comment]
FYI: Not sure if some of this change is still relevant, but I added the "colorspace" parameter emit for (Arnold) OSL a ways back for the ADSK repo: PR (https://github.com/autodesk-forks/MaterialX/pull/1336) based on earlier discussions on this topic.

**Comment by niklasharrysson** [comment]
@bernardkwok Thanks for that info! It seems most of this support you added has been merged to the default OSL code generator. So we can then control the current color management node insertion with the option you added.

**Comment by niklasharrysson** [comment]
@ZapAndersson Yes, since Bernard already added support for disabling the current CM system, we could just add in the missing parameters for the OSL texture call. So when there is a version of OSL that support this you can disable the current CM nodes and let OSL handle it internally.

I'll make that change in another PR since it's only semi-related to this one.

**Comment by jstone-lucasfilm** [comment]
Thanks to @niklasharrysson for the improvements in #1546 and #1547, and I'll mark this issue as resolved.  Let us know how these improvements work for you, @ZapAndersson, and feel free to post additional issues as needed.
