### ISSUE TITLE
Graph Editor: connecting separate outputs to combine inputs

### ISSUE THREAD

**Issue by marwie** [AcademySoftwareFoundation/MaterialX#1469]
Hello, just tried to see how separate and combine are setup and tried to connect separate outputs to combine inputs directly. 

I'm not sure if this is supported or how the outputs from the separate node can be accessed / used

created graph:
![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/b33e3d11-9af2-4352-bdc5-3e7a9e7f749f)

saved material:
```xml
<?xml version="1.0"?>
<materialx version="1.38">
  <separate3 name="separate3_vector3" type="multioutput" xpos="5.050725" ypos="-2.000000">
    <input name="in" type="vector3" nodename="constant_vector3" />
  </separate3>
  <constant name="constant_vector3" type="vector3" xpos="3.405797" ypos="-1.965517" />
  <combine3 name="combine3_vector3" type="vector3" xpos="7.094203" ypos="-2.034483">
    <input name="in1" type="float" value="0" />
    <input name="in2" type="float" nodename="separate3_vector3" />
    <input name="in3" type="float" value="0" />
  </combine3>
</materialx>
```

loading the saved material:
![image](https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/4a506245-c956-4d54-a540-369083091333)

**Comment by kwokcb** [comment]
This is definitely creating the incorrect graph. 

Not sure why. It should look like this:
```xml
<?xml version="1.0"?>
<materialx version="1.38">
  <separate3 name="separate3_vector3" type="multioutput" xpos="5.050725" ypos="-2.000000">
    <input name="in" type="vector3" nodename="constant_vector3" />
  </separate3>
  <constant name="constant_vector3" type="vector3" xpos="3.405797" ypos="-1.965517" />
  <combine3 name="combine3_vector3" type="vector3" xpos="7.094203" ypos="-2.034483">
    <input name="in1" type="float" nodename="separate3_vector3" output="outy" />
    <input name="in2" type="float" nodename="separate3_vector3" output="outx"/>
    <input name="in3" type="float" nodename="separate3_vector3" output="outz"/>
  </combine3>
</materialx>
```

For reference, a downstream node which references an upstream node (like `separate`) with multiple outputs needs to specify both it's upstream node / nodegraph and the name of the output to disambiguate.

**Comment by marwie** [comment]
Thanks a lot for the quick reply!!

**Comment by jstone-lucasfilm** [comment]
This is a great catch, @marwie, and this issue would be very worthwhile to address!

**Comment by jstone-lucasfilm** [comment]
This is a great catch, @marwie!  I'm CC'ing @lfl-eholthouser for her thoughts and recommendations, and I'd agree this is a worthwhile issue to address.

**Comment by lfl-eholthouser** [comment]
Thanks for flagging this @marwie, The Graph Editor doesn't currently support nodes with multiple outputs so while the graph is incorrect it's expected in a sense since the implementation is not there. I agree with @jstone-lucasfilm that this is a very valuable issue to address.

**Comment by kwokcb** [comment]
It does sound like the UI can support the load / display of the links. 
The connection logic is probably just setting incorrect information on the MaterialX document itself. 
If that's the case then we can this for now, but seems like just a localized fix is required.

**Comment by jstone-lucasfilm** [comment]
Got it, thanks @kwokcb, and it's sounding like this is just a bug in the step that interprets multioutput graph edits as MaterialX document edits.

This seems like a strong candidate for issues to address in 1.38.8, and if anyone has the bandwidth to take a look, let us know!

**Comment by kwokcb** [comment]
I'm taking a quick look: Seems both link breakage and link addition are incorrect.

**Comment by jstone-lucasfilm** [comment]
Thanks @kwokcb!
