### ISSUE TITLE
glTf textured nodes can not be used if the renderer uses named UV streams

### ISSUE THREAD

**Issue by JGamache-autodesk** [AcademySoftwareFoundation/MaterialX#1486]
The `uvindex` port found in the recently added glTf texture nodes (image, normalmap, iridescence...) deviates from the standard MaterialX convention of using a `texcoord` port that defaults to `defaultgeomprop="UV0"`

This makes them difficult to use in USD without extensive NodeGraph patching to replace `texcoord` nodes with multiple `geompropvalue` nodes that are selected from a `switch` node to remap UV index 0 - X to primvar names `st`, `st1`, `st2`...

**Comment by kwokcb** [comment]
Hi @JGamache-autodesk,
- glTF has no concept of `geomprop` and is not mappable to anything other than uvsets which are not named. With a generic `texcoord` anything can be mapped to it. 
 - The tooling to go to/from glTF thus becomes more complex (I guess similar kind of mapping is required to go to numbers somehow based on a string).
 
Perhaps this could be changed to be named "texcooord" with an enumeration then that maps "UV0,....UVN" to 0...N with a default of "UV0". Then it's still a string based reference and interop to glTF has a implicit mapping w/ no connections allowed ?

**Comment by kwokcb** [comment]
Thanks for the detailed info. 

Let make this consistent with `texcoord`.

@JGamache-autodesk: As a check, as there is no geometry context in MaterialX, when importing a number I guess the best it can do is create a `geomprop` with the index itself or "UV#".

**Comment by JGamache-autodesk** [comment]
I think replacing the `uvindex` integer input with a standard `texcoord` vector2 input would be the minimum change required to get name based clients unstuck

Your suggestion to add some name-based helper code in the shadergen is a great idea! I like it.

One way to do it would have the [TexcoordNodeGlsl](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/source/MaterialXGenGlsl/Nodes/TexCoordNodeGlsl.cpp) behave like a [GeomPropValueNodeGlsl](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/source/MaterialXGenGlsl/Nodes/GeomPropValueNodeGlsl.cpp) whenever a preference for name based UVs is declared in the GenOptions. That options could point to a `std::function<std::string(int)>` that would be provided by the downstream shadergen client to remap integer index to a name.

**Comment by JGamache-autodesk** [comment]
This might also be extendable to other index based nodes like GeomColorNodeGlsl.

**Comment by kwokcb** [comment]
I think we can look at this for another change. So maybe log a new issue for this.

For now it's easy to change the definitions first.

@jstone-lucasfilm , I assume to perform an upgrade to patch old files a PR is required in the 1.39 branch ?https://github.com/AcademySoftwareFoundation/MaterialX/tree/dev_1.39

I don't think a whole lot of folks are using `uvindex` but version upgrade would add a `texcoord` node with the same index (if not 0). 

Let me know. Thanks.
