### ISSUE TITLE
CGLTF loader does not load in multiple color or texcoord sets

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1495]
Unsure if this was changed or not but the sample GLTF does not load in multiple CPV or UV sets
from a glTF file.

There is code to handle this but it blocked by an early exit to halt multiple set loading.

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @kwokcb, as well as for the fix in #1517.
