### ISSUE TITLE
Add an XSD schema for MaterialX

### ISSUE THREAD

**Issue by vpenades** [AcademySoftwareFoundation/MaterialX#1531]
Being MaterialX an XML format, does it have an XSD schema from which we can generate classes for serialization?

I've looked around and I couldn't find any.

**Comment by jstone-lucasfilm** [comment]
Not yet, @vpenades, and I'd be interested in your thoughts on potential use cases for this feature.

**Comment by vpenades** [comment]
Well... when working with XLSX schemas there's usually two separate cases:  generic document validation, and generation of serialization classes.

With an XLSX schema, you can validate a document against the schema to check whether the document meets the specification.

But the use case I am interested in is to be able to parse materialX documents from C# ...  Right now, I would have to port all the C++ code to C# in order to do so.

But having an XLSX schema, the classes can be generated automatically for any language, allowing MaterialX to be read and written from/to any language other than C++ in a very easy way.

**Comment by jstone-lucasfilm** [comment]
@vpenades While I'm open to these ideas, it's worth noting that an XSD would only be capable of capturing a tiny fraction of the rules in the [MaterialX specification](https://github.com/AcademySoftwareFoundation/MaterialX/tree/main/documents/Specification), which include rules for strongly-typed connections between the nodes in a hierarchy of graphs.

If you're working in Python, you can install MaterialX on the command line with `pip install MaterialX`, and can then validate a document against the full set of MaterialX rules with just a few lines of code:

```
import MaterialX as mx
doc = mx.createDocument()
mx.readFromXmlFile(doc, filename)
(valid, message) = doc.validate()
```

Similar validation commands are available in C++ and JavaScript, and this is how clients of MaterialX typically check the validity of documents they are generating or exporting from applications.

**Comment by jstone-lucasfilm** [comment]
I'll close out this issue for now, as the approach described above allows a developer to validate a MaterialX document with a few lines of Python code, but I'm open to revisiting this idea in the future.
