### ISSUE TITLE
Graph Editor: Add Node popup restructure

### ISSUE THREAD

**Issue by lfl-eholthouser** [AcademySoftwareFoundation/MaterialX#1541]
The add node popup can be confusing for users. To combat this the order of the categories should be changed to better match  specification documents, e.g. Source Nodes (Texture, procedural, geometric, etc.) first, then Operator Nodes (math, adjustment, compositing, conditional, channel, etc.), then organizational and nodegraph-like nodes, then Shader BSDF Nodes, Shader EDF Nodes, etc. followed by Material nodes, etc. Also instead of having multiple nodes of each type for add etc have a second sub group of just add and then have all of the types of add within that.

**Comment by beersandrew** [comment]
I'm going to take a look at this issue during Dev Days 2023

**Comment by beersandrew** [comment]
Associated PR: https://github.com/AcademySoftwareFoundation/MaterialX/pull/1562
