### ISSUE TITLE
Graph Editor: Add floating popup to pins when hovered

### ISSUE THREAD

**Issue by lfl-eholthouser** [AcademySoftwareFoundation/MaterialX#1543]
To improve usability and remove uncertainty regarding UiNode pins without needed to always look at the node property, a floating window or static info pane indicating the Type of the input/output, and either its value (if set, or the default value if not) or "Connected to out" if it's connected when hovering over node input or node ouput would be extremely useful.

**Comment by ethomare-ilm** [comment]
Hi, I’m interested in doing the Graph Editor: Add floating popup to pins when hovered task for DevDays next week as a good first issue!
