### ISSUE TITLE
Attribute strings for various Element classes missing from Python API

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1545]
## Issue

- There are a number of classes which do not expose the static attribute enumeration strings.
- This includes the Element class and various derived classes.

## Effect

- Without these exposed, users need to find out what these are called and hard-code them. 
- If the attribute names change in the future then their code may break due to hard-coded string usage.
- This could help with performance as well by encouraging string reuse.

## Proposal

- Scan through and add these to the Python API.

**Comment by jstone-lucasfilm** [comment]
Sounds good, @rherrera-ilm, and welcome!
