### ISSUE TITLE
Create MTLX file from textures in a directory

### ISSUE THREAD

**Issue by Cinifreak** [AcademySoftwareFoundation/MaterialX#1556]
I made an example for that feature a while ago. @jstone-lucasfilm and @bernardkwok found it interesting. So, I can contribute it as joining Dev-Days.

The idea is to have a python script to create a MTLX NodeGraph from textures in directory with educated guess according to the best shading model match to that textures.

By default, we will have a relative paths for textures with optional flags to make it absolute.
Also, there will be another optional flag to force it to use a specific shading model configuration. if not, the script will make it's educated guess for the best match.

**Comment by jstone-lucasfilm** [comment]
Thanks for this original proposal, @Cinifreak, and this is now addressed in #1746.
