### ISSUE TITLE
Support two-way connections by allowing connections to be dragged from input to output ports

### ISSUE THREAD

**Issue by HudsonHN** [AcademySoftwareFoundation/MaterialX#1564]
Connections only work one-way / connections can not be made by dragging *Input* to *Output* ports

Please also see the comment below: https://github.com/AcademySoftwareFoundation/MaterialX/issues/1398#issuecomment-1684194636

Allow connecting ports by dragging input over output port

https://github.com/AcademySoftwareFoundation/MaterialX/assets/5083203/7d690588-e5ab-44c2-b161-f21f95e2ea0d

_Originally posted by @marwie in https://github.com/AcademySoftwareFoundation/MaterialX/issues/1398#issuecomment-1680203806_

**Comment by jstone-lucasfilm** [comment]
Thanks for calling out this subtask, @HudsonHN, and I believe this has now been addressed by @erikaharrison-adsk in #1569.
