### ISSUE TITLE
GraphEditor HiDPI scaling applied twice on MacOS

### ISSUE THREAD

**Issue by virokannas** [AcademySoftwareFoundation/MaterialX#1585]
On MacOS, the automatic DPI scaling that gets applied results in a double-scaled UI. An example:
![Screenshot 2023-10-26 at 2 13 22 PM](https://github.com/AcademySoftwareFoundation/MaterialX/assets/38055305/d34f3caf-43cb-49a6-ad26-ede2b41116f9)

This screenshot is taken on a 4K screen running at 2560x1440 logical resolution.

A simple solution would be just to skip the DPI scaling set up in Main.cpp under the comment "Handle DPI scaling" - this results in normal-sized UI components.

**Comment by simpassi** [comment]
Sent pull request #1586 to address this.

**Comment by jstone-lucasfilm** [comment]
Thanks for the fix, @virokannas, and this is now addressed in #1586.
