### ISSUE TITLE
Swizzle node inside nodegraph ignored edits to 'channels'

### ISSUE THREAD

**Issue by leekerley** [AcademySoftwareFoundation/MaterialX#1598]
When using a `swizzle` node inside a nodegraph it appears that editing the `channels` input via the `interfacename` attribute convention doesn't work.

I've only tested this in the Metal shader generator, but if I'm understanding the code I think it would affect all shader generators.  It appears that the Swizzle shader generator node is directly querying the `channels` input parameter value at shader code generation time ([source code](https://github.com/AcademySoftwareFoundation/MaterialX/blob/83ae82eefa9e34e081f1341e34b194e84ad5b151/source/MaterialXGenShader/Nodes/SwizzleNode.cpp#L39)), and only querying this directly from the node that's being generated, ignoring any upstream edits that might affect the node.

The file below demonstrates the problem
```
<?xml version="1.0"?>
<materialx version="1.38">

<nodedef name="ND_mySwizzle" node="mySwizzle" nodegroup="channel">
    <input name="in" type="float" value="0.0" />
    <input name="channels" type="string" value="rrr" uniform="true"  />
    <output name="out" type="color3" default="0.0, 0.0, 0.0" />
</nodedef>

<nodegraph name="IM_mySwizzle" nodedef="ND_mySwizzle">
    <swizzle name="my_swizzle" type="color3">
        <input name="in" type="float" interfacename="in"/>
        <input name="channels" type="string" interfacename="channels"/>
    </swizzle>
    <output name="out" type="color3" nodename="my_swizzle"/>
</nodegraph>

<mySwizzle name="test_node" type="color3">
    <input name="in" type="float"  value="0.85"/>
    <input name="channels" type="string"  value="00r"/>
</mySwizzle>

<oren_nayar_diffuse_bsdf name="diffuse_bsdf" type="BSDF">
    <input name="color" type="color3" nodename="test_node" />
</oren_nayar_diffuse_bsdf>
<surface name="surface_constructor" type="surfaceshader">
    <input name="bsdf" type="BSDF" nodename="diffuse_bsdf" />
</surface>
<surfacematerial name="test_material" type="material">
    <input name="surfaceshader" type="surfaceshader" nodename="surface_constructor" />
</surfacematerial>
</materialx>
```
![broken_swizzle_nodegraph](https://github.com/AcademySoftwareFoundation/MaterialX/assets/6572179/ec1f252e-ad59-496b-89d1-7e9715eaf771)

Notice here we get the image we would expect if `channels` is `rrr` which is the default specified inside the node definition, that should be being over written by the input specified on the `test_nodegraph` node.

I would expect it to generate the same image as this file

```
<?xml version="1.0"?>
<materialx version="1.38">

<swizzle name="test_node" type="color3">
    <input name="in" type="float"  value="0.85"/>
    <input name="channels" type="string"  value="00r"/>
</swizzle>

<oren_nayar_diffuse_bsdf name="diffuse_bsdf" type="BSDF">
    <input name="color" type="color3" nodename="test_node" />
</oren_nayar_diffuse_bsdf>
<surface name="surface_constructor" type="surfaceshader">
    <input name="bsdf" type="BSDF" nodename="diffuse_bsdf" />
</surface>
<surfacematerial name="test_material" type="material">
    <input name="surfaceshader" type="surfaceshader" nodename="surface_constructor" />
</surfacematerial>
</materialx>
```
![working_swizzle_node](https://github.com/AcademySoftwareFoundation/MaterialX/assets/6572179/368259bb-a960-4614-85b2-80eced2bf525)

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @ld-kerley, and I believe we can close this issue as `swizzle` nodes have been removed from MaterialX 1.39 in https://github.com/AcademySoftwareFoundation/MaterialX/pull/1793.
