### ISSUE TITLE
Interoperability of visual appearance between applications using MaterialX should not require knowledge of the authoring application's coordinate system conventions

### ISSUE THREAD

**Issue by hybridherbst** [AcademySoftwareFoundation/MaterialX#1626]
Looking a bit more into MaterialX for interoperability of materials between tools, I noticed that the MaterialX spec itself doesn't seem to describe what coordinate system is assumed, both for 3D data (position, normal; could be Y-up or Z-up or any of like 16 other combinations) ~~and surface data (UV coordinates; could start top-left or bottom-left or ...)~~.

**EDIT:** UV-to-texture is [defined here](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/documents/Specification/MaterialX.Specification.md#texture-nodes).

I understand that this may be in line with the wish for being non-opinionated, however, I think it is a huge problem when looking at MaterialX as a hopefully future standard for material interchange and things looking the same.

Are there any plans to increase the chance for things looking the same when using MaterialX across applications with various coordinate system conventions? Is it intended that MaterialX doesn't define any of this, and also doesn't define what spaces were used when authoring a file, or is this an oversight?

Here's a very simple example .mtlx that looks different depending on which app you're viewing it in: [MyLitGraph-position.mtlx.zip](https://github.com/AcademySoftwareFoundation/MaterialX/files/13781944/MyLitGraph-position.mtlx.zip)

Here is the above file viewed in a couple different applications with different underlying coordinate systems (you can clearly see the coordinate system flips):

| MaterialX Viewer | Unity | three.js |
| - | - | - |
| <img width="486" alt="positionNode-materialXviewer" src="https://github.com/AcademySoftwareFoundation/MaterialX/assets/2693840/f2c7df24-1aa1-4396-bfef-d339e4622306"> | <img width="385" alt="positionNode-Unity" src="https://github.com/AcademySoftwareFoundation/MaterialX/assets/2693840/39899df1-03ea-4969-bbc9-e30ac905309b"> | <img width="439" alt="positionNode-threejs" src="https://github.com/AcademySoftwareFoundation/MaterialX/assets/2693840/c46d4554-2c07-4ee9-964c-8ded6407b374"> |

**Comment by jstone-lucasfilm** [comment]
Thanks for bringing this up, @hybridherbst, and there's a good discussion of this question on the MaterialX channel of the ASWF Slack:

https://academysoftwarefdn.slack.com/archives/C0230LWBE2X/p1703716666685209

I'll close out the GitHub Issue for now, so that we don't need to keep it in sync with the evolving Slack discussion, and we can post new issues for any proposals for new engineering work that arise there.
