### ISSUE TITLE
Desktop entries and mime types for MaterialX Graph Editor and View

### ISSUE THREAD

**Issue by giandex** [AcademySoftwareFoundation/MaterialX#1627]
Hi, I apologize if this is the wrong place for my question, I'm not expert with the github environment.
I'm going to be the maintainer of MaterialX for Slackware, the slackbuild for build and install the package is almost ready, I have to do some tweaks and add support for some extensions (e.g. OpenImageIO). At the moment the installation including the graphical interfaces and python bindings seems works fine and I think that the slackbuild will be available soon in Slackbuilds.org, the repository of the software not included in the official Slackware releases.

I have a little problem. I made the desktop entries for the graphical interfaces but I'm not able to set the correct values for the [mimetype] key because I'm not expert in this subject. The values that I tried to add seem no working. Could help me to set the correct values?

These are the codes:

MaterialXView.desktop
`
[Desktop Entry]
Type=Application
Name=MaterialXGView
GenericName=MaterialX Viewer
GenericName[de]=MaterialX Viewer
GenericName[es]=Visor de MaterialX
GenericName[fr]=Visionneuse de MaterialX
GenericName[it]=Visualizzatore di MaterialX
GenericName[pt]=Visualizador de MaterialX
Comment=Interface for viewing GLSL shaders for MaterialX
Comment[de]=Schnittstelle zum Anzeigen von GLSL-Shadern für MaterialX
Comment[es]=Interfaz para ver sombreadores GLSL para MaterialX
Comment[fr]=Interface de visualisation des shaders GLSL pour MaterialX
Comment[it]=Interfaccia per la visualizzazione di ombreggiatori GLSL per MaterialX
Comment[pt]=Interface para visualização de shaders GLSL para MaterialX
Exec=MaterialXView %f
Icon=/usr/share/icons/hicolor/256x256/apps/materialx.png
Terminal=false
Categories=Graphics;
StartupNotify=true
MimeType=application/x-mtlx;model/materialx;application/x-materialx;application/xml;image/mtlx+xml;

`
and MaterialX Graph Editor
`
[Desktop Entry]
Type=Application
Name=MaterialXGraphEditor
GenericName=MaterialX Graph Editor
GenericName[de]=MaterialX Grafikeditor
GenericName[es]=Editor de Gráficos MaterialX
GenericName[fr]=Éditeur de Graphique MaterialX
GenericName[it]=Editor di Grafica MaterialX
GenericName[pt]=Editor Gráfico MaterialX
Comment=MaterialX graphics processing interface
Comment[de]=MaterialX Grafikverarbeitungsschnittstelle
Comment[es]=Interfaz de procesamiento de gráficos MaterialX
Comment[fr]=Interface de traitement de graphique MaterialX
Comment[it]=Interfaccia per l'elaborazione di grafica MaterialX
Comment[pt]=Interface de processamento gráfico MaterialX
Exec=MaterialXGraphEditor %f
Icon=/usr/share/icons/hicolor/256x256/apps/materialx.png
Terminal=false
Categories=Graphics;
StartupNotify=true
MimeType=application/x-mtlx;model/materialx;application/x-materialx;application/xml;text/mtlx+xml;image/mtlx;

`
Thanks
Giancarlo

**Comment by jstone-lucasfilm** [comment]
Good to meet you, @giandex, and one good forum for this question would be the MaterialX channel of the ASWF Slack, which is free to join:

https://www.aswf.io/get-involved/

There have been related question on that forum about the MaterialX filetype in the Apple ecosystem, and others in the MaterialX community may be able to point you in the right direction.

**Comment by giandex** [comment]
Thanks for the reply, @jstone-lucasfilm, I've posted the question in the suggested forum, waiting for a possible help I'll try anyway a solution myself throw the documentation about the mime type standards. I found also a build failure trying to add the support of OpenImageIO to MaterialX View, but before reporting the issue here I want to investigate the context better, because I'm not sure if it is generated by the build settings or the version of cmake used (3.28.1); cmake fails in a post build operation if I add explicitly a flag for the OIIO root directory (I think needed to activate a build condition). Without this flag MaterialX View cannot open files with OIIO support in runtime. I'll ve open a specific issue report when I've all elements.  Thanks :-)

**Comment by jstone-lucasfilm** [comment]
Thanks for starting the discussion on the MaterialX channel of the ASWF Slack, @giandex, and I'll provide a link here:

https://academysoftwarefdn.slack.com/archives/C0230LWBE2X/p1704012334874289

In order to keep that discussion focused, I'll close out the original GitHub Issue, but feel free to post new issues to represent any proposed MaterialX improvements that arise from that thread.
