### ISSUE TITLE
Incomplete build or build failure with support of OpenImageIO

### ISSUE THREAD

**Issue by giandex** [AcademySoftwareFoundation/MaterialX#1629]
Hi, as said in another context, I'm creating the package building tool for installing MaterialX in Slackware distribution, but I ran into an issue adding the support to OpenImageIO.
Adding the option -DMATERIALX_BUILD_OIIO=ON the build ends successfully, but if I didn't misunderstand, the option -DMATERIALX_BUILD_OIIO=ON should add a feature to the MaterialX View  (something like "open with OIIO"). I suppose by adding the functionality of the OIIO's executable iv in MaterialXView, but nothing of this appears in runtime. I investigated about this and in source/MaterialXView/CMakeLists.txt, at the line 146 there is this condition 
``````
if(MATERIALX_BUILD_OIIO AND OPENIMAGEIO_ROOT_DIR)
    add_custom_command(TARGET MaterialXView POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_directory
        ${OPENIMAGEIO_ROOT_DIR}/bin ${CMAKE_BINARY_DIR}/bin)
endif()
``````

I think that this should add the OIIO support to View, but this code is not handled because the cmake pre-configuration does not set the variable OPENIMAGEIO_ROOT_DIR (its value is empty).
So, I passed to cmake another additional flag, -DOPENIMAGEIO_ROOT_DIR=/usr (in the standard of Slackware distributions all the executables files are installed in /usr/bin).
Adding -DOPENIMAGEIO_ROOT_DIR=/usr allow to process the above conditional subroutine, but the build gives this error:
``````
[ 62%] Building CXX object source/MaterialXView/CMakeFiles/MaterialXView.dir/Viewer.cpp.o
[ 62%] Linking CXX executable ../../bin/MaterialXView
Error copying directory from "/usr/bin" to "/tmp/SBo/MaterialX-1.38.8/build/bin".
make[2]: *** [source/MaterialXView/CMakeFiles/MaterialXView.dir/build.make:166: bin/MaterialXView] Errore 1
make[2]: *** Eliminazione del file «bin/MaterialXView»
make[1]: *** [CMakeFiles/Makefile2:1159: source/MaterialXView/CMakeFiles/MaterialXView.dir/all] Errore 2
make: *** [Makefile:146: all] Errore 2
``````
The build log of make reports this:
``````
163 bin/MaterialXView: source/MaterialXView/CMakeFiles/MaterialXView.dir/link.txt
164         @$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir=/tmp/SBo/MaterialX-1.38.8/build/CMakeFiles --progress-num=$(CMAKE_PROGR>
165         cd /tmp/SBo/MaterialX-1.38.8/build/source/MaterialXView && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/MaterialXView.dir/link.txt --verbose=$(VERBOSE)
166         cd /tmp/SBo/MaterialX-1.38.8/build/source/MaterialXView && /usr/bin/cmake -E copy_directory /usr/bin /tmp/SBo/MaterialX-1.38.8/build/bin
167
168 # Rule to build all files generated by this target.
169 source/MaterialXView/CMakeFiles/MaterialXView.dir/build: bin/MaterialXView
170 .PHONY : source/MaterialXView/CMakeFiles/MaterialXView.dir/build
171
172 source/MaterialXView/CMakeFiles/MaterialXView.dir/clean:
173         cd /tmp/SBo/MaterialX-1.38.8/build/source/MaterialXView && $(CMAKE_COMMAND) -P CMakeFiles/MaterialXView.dir/cmake_clean.cmake
174 .PHONY : source/MaterialXView/CMakeFiles/MaterialXView.dir/clean
175
176 source/MaterialXView/CMakeFiles/MaterialXView.dir/depend:
177         cd /tmp/SBo/MaterialX-1.38.8/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /tmp/SBo/MaterialX-1.38.8 /tmp/SBo/MaterialX-1.38.8/source/MaterialXVi>
178 .PHONY : source/MaterialXView/CMakeFiles/MaterialXView.dir/depend
179
180
``````
This happens in two different systems: in Slackware64 -current (the testing release of the distribution, that I use by default), with cmake version 3.28,1, and Slackware64 15.0 (the latest stable release, that I use to test the installation packages), with cmake version 3.21.4

Both the systems have installed OpenImageIO version 2.2.21.0 and similar build/install configuration for MaterialX, with these flags:
``````
    -DCMAKE_C_FLAGS:STRING=-O2 -fPIC  
    -DCMAKE_CXX_FLAGS:STRING=-O2 -fPIC  
    -DCMAKE_INSTALL_PREFIX=/usr/share/MaterialX 
    -DMATERIALX_BUILD_SHARED_LIBS=ON 
    -DMATERIALX_INSTALL_LIB_PATH=../../lib64
    -DMATERIALX_BUILD_OIIO=ON 
    ( -DOPENIMAGEIO_ROOT_DIR=/usr )   // this gives the build failure
    -DMATERIALX_BUILD_VIEWER=ON 
    -DNANOGUI_PREFERRED_BACKEND=OpenGL   
    -DMATERIALX_BUILD_GRAPH_EDITOR=ON 
    -DMATERIALX_BUILD_PYTHON=ON 
    -DMATERIALX_INSTALL_PYTHON=ON 
    (  -DCMAKE_POLICY_DEFAULT_CMP0148=OLD )  // only with cmake 3.28.1, it removes a warning 
    -DCMAKE_BUILD_TYPE=Release ..

``````

The install tree follows the standard of Slackware (strictly Unix-like):

/usr/install                           (installation files, set in post installation, handled and needed by the Slackware's package manager)
/usr/doc/MaterialX-1.38.1  (documentation and license files, set in post build)
/usr/bin                                (symbolic links to Graph Editor and View executables added in post build)
/usr/include                         (symbolic link to /usr/share/MaterialX/include added in post build)
/usr/lib64                             (shared libraries of MaterialX and .cmake files, set in CMake pre-configuration)
/usr/share/MaterialX         (the full installation path, set in CMake pre-configuration)
/usr/share/applications    (desktop entries, added in post build)
/usr/share/icons/...            (icon based on MaterialX logo, added in post build)

That's is all. Please notify me any question on additional elements referring the context. Thanks

**Comment by kwokcb** [comment]
Hi @giandex,
I think the issue lies with the assumption that only the OpenImageIO libraries reside under the "bin/" folder and can be copied to the build area. (I've only ever built with OIIO on Windows using vcpkg where this assumption holds true).

Can you try to remove this copy dir logic as I assume that since OpenImageIO is installed that is in your library search path and will be found when running the viewer. You don't want to try and copy your entire usr/bin to the build area :). 

Hope this helps.

**Comment by giandex** [comment]
Thanks kwokcb, you are right! I did some tests with these steps
First test
1) as administrator I created a temporary directory /osr/bin in the filesystem root
2) in this directory I create a symbolic link for each executable file installed by OIIO. The package installed includes 8 executables: `iconvert  idiff  igrep  info  iv  maketx  oiiotool  testtex`
3) then I launched the slackbuild with the flag ` -DOPENIMAGEIO_ROOT_DIR=/osr ` but the build still failed
I checked in the build directory created by cmake and I saw that only the executable `oiio`  has been copied, so I presumed that the issue could be caused by one of the other seven executables

Second test (I've been lucky)
1) from /osr/bin I removed the symbolic link to testtex 
2) I started the slackbuild again (with the same flag as above) and the build ended successfully!
3) I've installed the rebuilt package and MaterialX View works fine
4) I removed the directory /osr/bin and the View works still

This solves the issue: I have to add in the slackbuild script a procedure that creates a temporary folder with the symlinks to the seven OIIO executables. The same script will remove this temporary folder at the end of the build.

Now only a doubt remains: the interface of View seems no have changes, no references to OIIO appears in the interface, neither in the Advanced Settings. Is the OIIO functionality perhaps implicitly included in View? This is not really important for me as user, since I'm not expert in computer graphic. As maintainer of the installation package, my primary objective is make a functional build procedure that can provide a package as complete and implemented as possible.

Thanks for your help, very precious! 
I think that issue can be closed :-)

**Comment by kwokcb** [comment]
Hi @giandex,

- Sorry, I forgot to mention that this build option merely changes the plug-in image handler which is used to load and save files. So you won't see anything different from a UI point of view.

- To check that it works you can try to load in a sample file which has a file input and then try and load in an `exr` file (which is not handled by the default image loader).
A simple example can be found [here](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/resources/Materials/TestSuite/stdlib/texture/image_codecs.mtlx):

**Comment by giandex** [comment]
Well, it works! When the dialog window (zenity) open, it lists also the format *.exr and View loads the example you have mentioned 
thanks again :-)

**Comment by jstone-lucasfilm** [comment]
Thanks for that guidance, @kwokcb, and I'll go ahead and mark this as resolved.
