### ISSUE TITLE
SUG: Make Web Viewer more known publicly

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1639]
## Issue

It is quite hard to know that there is a Web viewer for MaterialX.

## Suggestion

Unless you go into the github repo or know of the site, the WebViewer is quite hard to discover / find the site
(https://academysoftwarefoundation.github.io/MaterialX/)

Suggestion is to make a link to this more public so users can find and try it out to expose MaterialX more broadly, 
perhaps by adding a mention at the top level github but also in the `materialx.org` site (which only mentioned the desktop viewer and not the node editor either).

**Comment by jstone-lucasfilm** [comment]
Great suggestions, @kwokcb, and I agree these changes would be valuable.  If developers in the community have the bandwidth to make these adjustments to the MaterialX and materialx-website GitHub repositories, feel free to write up pull requests.

**Comment by jstone-lucasfilm** [comment]
Looking at www.materialx.org, I see that we mention the MaterialX Web Viewer very briefly and provide a link, but this application definitely deserves its own section on the page:

https://materialx.org/Tools.html

**Comment by jstone-lucasfilm** [comment]
I've had a chance to refine our tools documentation for MaterialX, adding sections on the Graph Editor and Web Viewer:
https://materialx.org/Tools.html#WebViewer

I'll close out this original issue for now, though there's still plenty of room for future improvement in this area.
