### ISSUE TITLE
Add API call to convert channels attributes to nodes

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1652]
## Issue

It is possible to either miss or bypass the `channels` attribute on an `input`
If this occurs this can fail validation due to input / output type being found to be different types.

(Note: There also appears to be issues with how this attribute can sometimes not propagate properly 
with interface inputs and outputs.)

## Suggestion

Add a convenience utility to convert implicit `channels` attributes to explicit nodes (such as an `extract`, 
`swizzle` etc)

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @kwokcb, and I'll just add a note that this will be addressed by the design changes in MaterialX 1.39, which includes the replacement of `channels` attributes with explicit nodes.

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @kwokcb, and channels attributes have been removed from MaterialX 1.39 in https://github.com/AcademySoftwareFoundation/MaterialX/pull/1804.
