### ISSUE TITLE
Attribute `space` is ignored for `viewdirection` node

### ISSUE THREAD

**Issue by hybridherbst** [AcademySoftwareFoundation/MaterialX#1656]
Seems the `viewdirection` node has a `space` property but it actually doesn't do anything in https://academysoftwarefoundation.github.io/MaterialX/,

when modifying `space` to `model` | `object` | `world` the result is identical:
[edge_brighten copy.mtlx.zip](https://github.com/AcademySoftwareFoundation/MaterialX/files/13969701/edge_brighten.copy.mtlx.zip)

Is this intentional?

**Comment by jstone-lucasfilm** [comment]
Good catch, @hybridherbst, and it looks like only the OSL implementation of `viewdirection` supports the `space` property in the initial pull request.  This would be a much appreciated contribution if developers in the community have the bandwidth to extend this support to GLSL and MSL.

**Comment by jstone-lucasfilm** [comment]
Good catch, @hybridherbst, and it looks like only the OSL implementation of viewdirection supports the space property in the initial pull request. This would be a much appreciated contribution if developers in the community have the bandwidth to extend this support to GLSL and MSL.

https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/libraries/nprlib/genosl/nprlib_genosl_impl.mtlx#L15

**Comment by edobrowo** [comment]
Hello! I'd like to work on this issue for Dev Days.

**Comment by jstone-lucasfilm** [comment]
Thanks to @hybridherbst for this original report, and to @edobrowo for the fix in #2036!
