### ISSUE TITLE
Update UsdUVTexture to single-output signatures in 1.39

### ISSUE THREAD

**Issue by jstone-lucasfilm** [AcademySoftwareFoundation/MaterialX#1673]
This is a proposal to update the `UsdUVTexture` node to single-output signatures in MaterialX 1.39, allowing these nodes to robustly distinguish between `color3`, `color4`, `vector3`, and `vector4` outputs.  Version upgrade logic would be used to update UsdUVTexture references in earlier documents to the new node signatures.

Additional details on the background and motivation for this change can be found in #1372.

**Comment by jstone-lucasfilm** [comment]
@kwokcb @niklasharrysson @ld-kerley I'd like to include this update in MaterialX 1.39 if possible, since it involves a change in node signatures that requires version upgrade logic.  Let me know whether this proposal sounds reasonable to you all.

**Comment by ld-kerley** [comment]
No objections in general...

The USD spec appears to only have `float3` output - not `float4`.  So if we're being forward looking with 1.39, do we need to add `color4` and `vector4`? 

Is it also possible to keep a `multioutput` version of the node that exposes `float` ports for each of `r`,`g`,`b`,`a`? or does the presence of the `multioutput` node definition cause problems?

Is the code in the PR above the proposed change?  I noticed it was closed, so wasn't sure if there was going to be a new PR posted?

**Comment by jstone-lucasfilm** [comment]
@ld-kerley My current thinking is that I would post a new PR for this work, simplifying the `UsdUVTexture` node to single-output signatures in MaterialX 1.39, and recommending existing functionality such as `extract` and `separateN` when individual channels of a texture are needed.  We could then leverage the version upgrade system to correctly interpret `UsdUVTexture` nodes in legacy MaterialX documents.

We could potentially preserve a single multioutput version of the node (e.g. just the color4 version), but it seems more aligned with the MaterialX approach to provide this functionality through `extract` and `separateN`, so I'm imagining that we'd omit this for 1.39.

What are your thoughts?

**Comment by ld-kerley** [comment]
I'm sort wondering what the intended use-case for the USDPreviewSurface family of nodes inside MaterialX is.... I guess I always thought it was to allow someone to author a nodegraph that would be "portable" albeit with some code to transcode it - to a UsdShade material, not using MaterialX.  In that case perhaps leaning on `extract` or `separateN` isn't a viable path, as those nodes don't exist in the UsdShade specification.

That said, I could also get behind the idea of retaining one version of the `UsdUVTexture` node that adheres to the UsdShade specification as closely as possible, (i.e. float `r`,`g`,`b`,`a` and color3 `rgb` outputs), and just adding additional single output port types as you're proposing above to solve the stricter type connections in MaterialX that we encounter if a UsdShade texture node is connected to the `normal` port on `UsdPreviewSurface`.

I don't have strong objections to any of these approaches though, so take my input with a grain of salt.  I do wonder if the root of this issue, USD having a `float3` type as well as `color3f` and `normal3f`, indicates that maybe we might want to investigate allowing MaterialX to have a float tuple data type that did not have some implied semantic attached to it, and allow some more flexibility in conversion.

**Comment by jstone-lucasfilm** [comment]
Those are good questions, @ld-kerley, and perhaps we should indeed give this subject more thought before moving forward with a specific approach for 1.39.

For float tuple data without any associated semantic, though, wouldn't this simply be the `vector3` data type in MaterialX?  If we wanted to move `UsdUVTexture` to a tuple output type without any semantic, that would be the one I would choose, though I believe we would still need a distinction between color and vector types, to allow the correct interpretation of color space bindings.

**Comment by jstone-lucasfilm** [comment]
As another path forward, what if we were to leave the existing multi-output definitions of `UsdUVTexture` alone in MaterialX 1.39, and use the convention of assigning a `colorspace` of `none` when the color semantics of this node are not desired?  This would preserve the current quality that the `UsdUVTexture` definitions are exactly aligned between MaterialX and USD, as @ld-kerley suggests above.

**Comment by jstone-lucasfilm** [comment]
I've moved forward along this second path in PR https://github.com/AcademySoftwareFoundation/MaterialX/pull/1900, adding support for setting `colorspace` to `none` on UsdUVTexture nodes.

To my mind, this seems like a more robust approach, where the signature of UsdUVTexture remains unchanged in MaterialX 1.39, but we have the capability to disable colorspace transforms on a per-texture basis for normal maps and other vector use cases.

I'll close out this ticket as resolved, and let's see how this approach works out in practice.
