### ISSUE TITLE
Suggestion: Add way to determine MaterialX release used for shipped library / nodes

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1688]
## Issue

Currently if you just look at the shipped "standard" `libraries` folder there is no way to determine for what release it is used for. 

- It is possible to load in a random file and hope that the version indicated for the release but this is not guarantee.
- Also development or patch versions are not stored inside a file / document so nodes modified / added during a patch release are not discoverable at all.

Nodes themselves have no indication as to what version they belong to either, though they may have a creation version. (Note by default almost all nodes have not version so it needs to be assumed they are version "1".

## Proposal

- If possible it would be useful to at least include a release version with the libraries.
  - This could be the same version as provided as a C++ define or run-time string.
- Unsure what can be done with per nodes version correspondence.

**Comment by jstone-lucasfilm** [comment]
This is an interesting question, @kwokcb, and although we can modify our CMake build script to stamp the `README.md` in the `libraries` folder with the version of the associated MaterialX codebase, I'd be interested in whether this is something that MaterialX developers will often need.

Would it not be sufficient for developers to query the MaterialX version through C++, Python, or JavaScript, or by looking at the version in the CMake script in the root folder of the project?

**Comment by jstone-lucasfilm** [comment]
I'll close out this issue for now, since the mechanisms described above seem like reasonable ways for developers to access the MaterialX version, but I'm open to additional discussion on this topic in the future.
