### ISSUE TITLE
Suggestion: Add more Global Nodes

### ISSUE THREAD

**Issue by adro79** [AcademySoftwareFoundation/MaterialX#1791]
Hello! I'd like to get some information about your thoughts about adding more global type nodes like Curvature and Distance to the MaterialX.

As an Environment Artist, I use those types of shaders quite a lot to build complex materials. 
Now that Maya 2025 has implemented the [MaterialX Data Format](https://help.autodesk.com/view/MAYAUL/2025/ENU/?guid=GUID-5262DC69-3AAB-4CE9-8CA6-C80CA560F813 ) with Lookdevx, it's time to consider implementing it in my workflow.

I open this issue because I'm worried about not getting the full universalization of shaders that MaterialX purposes with complex shaders. Arnold and Karma are implementing their own render-specific mtlx nodes to face those limitations, breaking the compatibility between renders.

That being said, are there any plans regarding this? 

Thanks.

**Comment by jstone-lucasfilm** [comment]
@adro79 This is one of our main focuses going forward, reviewing and merging proposals for new MaterialX nodes from the community, and we'd appreciate any proposals that you have the bandwidth to write up.

Curvature is a feature we're very interested in, and I believe the main work will be coming up with a standard definition of this idea that holds its meaning across renderers.  Often curvature is implemented in terms of the "partial derivatives" of the `normal` and `position` vectors, so one path forward would be for a team to propose definitions of partial derivative nodes in MaterialX, which could then be used to robustly define a curvature node.

**Comment by adro79** [comment]
Thanks for the response, I'm glad to see this is something you're looking for.

Unfortunately I have no experience with these types of formulas, but I'm sure I would lend a hand if I could. Let's hope someone comes with a proposal to implement these features soon.

**Comment by jstone-lucasfilm** [comment]
No problem, @adro79, and we'll continue reviewing and merging new proposals for nodes as they're contributed by the community.

You can get a sense of the most recent contributions to MaterialX by looking at our release notes, with the contributions in 1.38.8 and 1.38.9 including shape nodes from SideFX and Autodesk, and the beginnings of a non-photorealistic rendering (NPR) node library.

https://github.com/AcademySoftwareFoundation/MaterialX/releases
