### ISSUE TITLE
Not all math functions are documented in the specification.

### ISSUE THREAD

**Issue by fpliu** [AcademySoftwareFoundation/MaterialX#1808]
Looking in v1.38 I don't see invert, distance, reflect or refract

**Comment by jstone-lucasfilm** [comment]
@fpliu That's a good reminder that we have recent node contributions that still need documentation.  Here's where that specification work is actively being developed for 1.39, and although I believe `invert` and `distance` have already been added, you're correct that we don't yet have `reflect` or `refract`.

https://github.com/AcademySoftwareFoundation/MaterialX/blob/dev_1.39/documents/Specification/MaterialX.Specification.md

I'm CC'ing @dbsmythe who has been tracking the alignment of our specification and codebase for 1.39, and of course we're open to contributions of language for these nodes from the community as well.

**Comment by dbsmythe** [comment]
Reflect and Refract are included in the big Specification update PR, https://github.com/AcademySoftwareFoundation/MaterialX/pull/1794 .  @jstone-lucasfilm - Are there any further concerns or discussions regarding that PR that need to be addressed?

**Comment by jstone-lucasfilm** [comment]
Ah, thanks @dbsmythe!  In that case, let's move forward with merging that change, and we can consider related code updates for future pull requests.

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @fpliu, and this has been addressed in #1809.
