### ISSUE TITLE
Graph Editor: Reproducible crash after renaming node

### ISSUE THREAD

**Issue by jstone-lucasfilm** [AcademySoftwareFoundation/MaterialX#1912]
Repro steps:

- Launch the Graph Editor with its default marble material.
- Click on the `NG_marble1` node and rename it to `NewMarble`.
- Double click on the `NewMarble` node to view its graph.
- Navigate back to the original view by clicking on the left angle bracket.
- Connect the output of `NewMarble` to the `base_color` input of `SR_marble1`.

**Comment by jsjtxietian** [comment]
Hi I'd like to tackle this one!

Since the crash is vertex out of bounds, a quick fix would be like this, if any node is invalid, just early out in `deleteLinkInfo`:
```C++
diff --git a/source/MaterialXGraphEditor/Graph.cpp b/source/MaterialXGraphEditor/Graph.cpp
index f2382e28..04ec66d8 100644
--- a/source/MaterialXGraphEditor/Graph.cpp
+++ b/source/MaterialXGraphEditor/Graph.cpp
@@ -2753,6 +2753,10 @@ void Graph::deleteLinkInfo(int startAttr, int endAttr)
     int upNode = getNodeId(startAttr);
     int downNode = getNodeId(endAttr);
 
+    if (upNode == -1 || downNode == -1) {
+        return ;
+    }
+
     // Change input to default value
     if (_graphNodes[downNode]->getNode())
     {
```

But the root cause seems to be that when navigate back to the original view after renaming and viewing, some connections are lost.

**Comment by jstone-lucasfilm** [comment]
Thanks for taking a look, @jsjtxietian, and a fix for that root cause would be much appreciated!
