### ISSUE TITLE
Graph Editor ImGui Delete Key

### ISSUE THREAD

**Issue by fruitTheory** [AcademySoftwareFoundation/MaterialX#1921]
Having trouble deleting nodes and wires in graph editor in both personal build and release build. After finding and testing code in Graph.cpp: `if (ImGui::IsKeyReleased(ImGuiKey_Delete) || _isCut)` line 4081 - Replacing ImGuiKey_Delete with ImGuiKey_0 or any other key seems to allow deletion to work upon rebuild. It doesn't work with wire but still looking into this. Using windows 11 OS and cmake for build, although had the same issue on MaterialX_Windows_VS2022_x64_Python311 release.

**Comment by jstone-lucasfilm** [comment]
Have you had any luck in tracking this down further, @fruitTheory?  If there's a bug with the handling of this key in the Graph Editor, we should have developers take a closer look.

**Comment by fruitTheory** [comment]
I have not, but I can investigate further today. I can't tell if it's just my keyboard because I feel like I've had this issue on other software node editors. But if anyone else can check if they have the same problem, maybe then developers can take a look.

**Comment by fruitTheory** [comment]
Well I somewhat figured it out. For me it needs to be ImGuiKey_KeypadDecimal, instead of ImGuiKey_Delete, which seems to not exist/output anything in any of the test cases. @jstone-lucasfilm

**Comment by fruitTheory** [comment]
Closing as personal hardware issue. Solution being remapping key locally. Code solution may not make sense to conflate delete key with period key.
