### ISSUE TITLE
Investigate removing the installation of 'resources' for MaterialXGenShader module

### ISSUE THREAD

**Issue by ld-kerley** [AcademySoftwareFoundation/MaterialX#1924]
Introduced [here](https://github.com/AcademySoftwareFoundation/MaterialX/commit/2036a4d9ea87b258ae6e47c4c85c6393fa76553f#diff-4dc49384c09daa9d9424d7387315f0f9f204bca72823eefb665f1958e7acac75), it appears `resources` are installed for `MaterialXGenShaders`.

We think they are only needed for `MaterialXRender` modules - see [here](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/CMakeLists.txt#L432)

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @ld-kerley, and this has been addressed in #1927
