### ISSUE TITLE
State of Material Inherits

### ISSUE THREAD

**Issue by dgovil** [AcademySoftwareFoundation/MaterialX#1933]
I just wanted to file an issue asking about the support for Material Inherits. 

I was resolving an [issue](https://github.com/PixarAnimationStudios/OpenUSD/issues/3100) in usdMtlx by [changing the names of translated nodes](https://github.com/PixarAnimationStudios/OpenUSD/pull/3147 ) that was caused by a heuristic to try and support Material Inherits.

The [MaterialX spec](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/documents/Specification/MaterialX.Specification.md#material-inheritance) says that this is a supported feature.

However in examining the MaterialX code base, it seems that this feature isn't tested anywhere, and I was having a hard time finding code that implemented the inheritance functionality. I also cannot find any sample files that use it, or any tools that make use of it publicly.

I wonder if this feature needs some work to fully flesh it out, or perhaps it might simplify heuristics to remove it from MaterialX?

**Comment by jstone-lucasfilm** [comment]
I think you're right, @dgovil, that this category of inheritance is not yet implemented in the MaterialX codebase.

Is it your sense that we ought to move forward and implement it in a future release, or that we ought to reconsider whether it's an important feature to preserve?

**Comment by dgovil** [comment]
Personally, I'm leaning towards removal and perhaps revisiting adding it at a later date should the need arise?

My rationale being that the addition within that current versions would be a significant change as to how content is handled for both editors and USD, and it's best to keep things simple for the time being?

**Comment by jstone-lucasfilm** [comment]
That sounds like a reasonable proposal to me, @dgovil, and I'm CC'ing @dbsmythe for his thoughts on making this change to the specification.

**Comment by ld-kerley** [comment]
At this point I think a general rule of thumb should be that if something is not implemented, then we should be removing it from the specification, or at least loudly documenting in the specification that its currently not implemented.

**Comment by dbsmythe** [comment]
Personally, I've been of the mind that the Specification should indicate what the **desired** functionality is, and it makes sense to me that inheriting materials in a manner similar to how other things can be inherited, is a worthwhile feature to try to support.
But I don't have any objection to having the Spec contain annotations along the lines of "_This feature has not yet been implemented_", so it's clear what features and nodes are actually available in the current library.

**Comment by jstone-lucasfilm** [comment]
@dbsmythe That's a completely reasonable approach, though given the much stronger industry dependencies on the MaterialX specification and codebase in 2024, I wonder if it makes more sense to consider them as a *unit*, where we make a concerted effort to exactly align the specification and codebase with each release of MaterialX.

Because our specification history is now recorded permanently on GitHub, there's no danger of losing access to the earlier definition of material inheritance if we later decide to add this feature, and at that point we would contribute it to the specification and codebase in a single commit, maintaining the level of consistency that we're now aiming to achieve.

**Comment by meshula** [comment]
In the core spec working group, we take a stance that we describe things as they are, and if we encounter things that need revision in the base implementation, or suggestions for improvement, we pass those downstream to the implementors. We do make note of them as well, but not in normative language:  we box them as "informative notes", typically in an Appendix, and we mention in our introduction that informative notes capture these sorts of things but are not normative.

**Comment by dgovil** [comment]
I think it would be really good to split out anything aspirational from in the spec. 

I think the bigger problem is what a "specification" means to the project. 

I think so far the specification has been both a document to standardize behaviour , but also a forward looking design specification. Unfortunately it hasn't clarified which of the two it is. 

By splitting the spec into those parts, or at least unambiguously calling out anything that is aspirational, it'll reduce a lot of the confusion that we've already been working to correct post-facto.

**Comment by ld-kerley** [comment]
I really like the idea of splitting up the main specification document too.  Having the specification completely align with what the code is implementing, and then having a separate document that describes desired future implementation would also make it a lot clearer to people who want to come and contribute to the project, what is working, and what areas the project has identified it would like to see contributions in expand currently implemented functionality.

I was also looking over the `documents/Specifications` folder, and we have separated out the nodes from `libraries/nprlib` and `libraries/pbrlib`.  I wonder if it also makes sense to separate out the `libraries/stdlib` node definitions from the current `MaterialX.Specification.md` document in to a separate document?

**Comment by jstone-lucasfilm** [comment]
@ld-kerley I like both of those suggestions, and focusing on the separation of the normative specification and desired future features, we might consider organizing the future features into a `MaterialX.Proposals` document.  This could then easily be extended with new proposals, without altering the normative specification defined in `MaterialX.Specification`.

**Comment by crydalch** [comment]
FWIW, I think in a USD-centric workflow, this MaterialX-centric inheritance may not be used as much? Specializes arcs to provide this same behavior, of building up more specialized materials from existing ones.

But for any lossless translation of concepts, I think it's good to point out that `specialize` arc in USD works the way that this inherits works in MaterialX (as the `inherit` arc is for broadcasting overrides, and has stronger opinions). Someone once explained specializes as "soft schemas", and that helped it solidify in my mind.

Is MaterialX inheritance only for "materials"? (i.e. `surfacematerial` or `volumematerial`) or does it work for any MaterialX primitive?

**Comment by dbsmythe** [comment]
The idea of a new, separate "MaterialX Proposals" document sounds good to me as well.  I would propose that this new document contain separate sections for proposals to each of the individual Specification documents, e.g. a section for the main Spec, a section for PBR, a section for NPR, a section for Geometry Extensions, etc.

I'm less convinced one way or the other about the value of splitting out the Stdlib node descriptions from the rest of the main Specification document, but it would be great to discuss the pros and cons here or in Slack.

**Comment by jstone-lucasfilm** [comment]
Now that @dbsmythe has moved this feature to the new MaterialX Proposals document, I believe we can mark this task as resolved, and material inheritance can now be considered a proposal for a future version of MaterialX.

**Comment by jstone-lucasfilm** [comment]
For reference, here's the new section of the MaterialX Proposals document that documents the goals for material inheritance in the future:

https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/documents/Specification/MaterialX.Proposals.md#material-inheritance
