### ISSUE TITLE
isTransparentSurface() does not work for OpenPBR

### ISSUE THREAD

**Issue by JGamache-autodesk** [AcademySoftwareFoundation/MaterialX#1946]
I suspect adding `transmission_weight` and `geometry_opacity` to the [OpaqueTestPairList](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/source/MaterialXGenShader/Util.cpp#L19) would fix this.

**Comment by kwokcb** [comment]
Shouldn't we be tagging the inputs accordingly based on the [spec](https://github.com/AcademySoftwareFoundation/MaterialX/blob/3a5b53b2915c15c2d5056a50cd03a2d885c20788/documents/Specification/MaterialX.Specification.md?plain=1#L2257)  otherwise this is very "brittle" ?

**Comment by JGamache-autodesk** [comment]
Definitely. I was not aware of the `hint` metadata until you pointed it to me. This is going to solve many issues.

**Comment by JGamache-autodesk** [comment]
I don't see any new code in [isTransparentShaderNode()](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/source/MaterialXGenShader/Util.cpp#L95C6-L95C29) that uses those hints though. And none of the surfaces in `bxdf` use the new spec. I guess the feature did not make it in 1.39.1.

**Comment by kwokcb** [comment]
I guess not. 

I'd suggest the following interface changes to Input:

1. Add a `Input.hasTransparencyHint()` and / or `Input.hasOpaqueHint()` and setters for completeness.
2. Add a `Node.getOpaqueHintList() on the node which can scan using methods in 1. to build a "opaque comparison" dictionary.
2. Call `getOpaqueHintList() [when testing](https://github.com/AcademySoftwareFoundation/MaterialX/blob/3a5b53b2915c15c2d5056a50cd03a2d885c20788/source/MaterialXGenShader/Util.cpp#L120)

**Comment by JGamache-autodesk** [comment]
Looks very good. Adding a bit of caching at the NodeDef level would help to make sure we do not rescan the list of inputs every time looking for the ones with hints.

**Comment by kwokcb** [comment]
I did not add in caching to keep this the logic for generic "hint" accessors and the transparency checking logic localized in the util.
