### ISSUE TITLE
MaterialXGraphViewer: `time_float` and `frame_float` do not have any effect

### ISSUE THREAD

**Issue by hybridherbst** [AcademySoftwareFoundation/MaterialX#1951]
I believe this graph should make the resulting object change color from black to white in a triangle wave shape:
<img width="1328" alt="image" src="https://github.com/user-attachments/assets/1eeccb98-2ab9-4dde-b712-156ad18e9eea">

However, it currently doesn't do anything, or I can't figure out how I can "play" the file in MaterialXGraphViewer (either just let time progress, or be able to scrub/set time somehow).

**Comment by kwokcb** [comment]
There is no "play" functionality here nor in the web viewer. For the hardware case the `u_frame` shader uniform needs to be updated and bound as mentioned [here](https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/documents/DeveloperGuide/ShaderGeneration.md)

**Comment by hybridherbst** [comment]
Then please consider it a feature request! – for realtime usage the "time" variable is quite oftenly used and I think it would be good to be able to test it in the easiest available "reference viewer".

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @hybridherbst!  Since this is a missing feature in our GLSL code generation, I'd like to merge this request with https://github.com/AcademySoftwareFoundation/MaterialX/issues/1951, and we can clarify the broader nature of the feature request there.
