### ISSUE TITLE
Proposal: Add a simple way to strip out library content on XML write

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#1991]
## Issue

Currently a document needs to import the standard libraries to use any of the node definitions available.
This get's embedded inside the working document. When writing to XML, this content get's embedded inside the
document which can often be undesirable.

You thus need to either create a write predicate function and pass this over to XmlWriteOptions or
traverse and prune yourself. This is highly dependent on knowing to look for items with source URIs.

## Proposal 1

Add a new convenience option on `XmlWriteOptions` to automatically strip out these libraries using a built in / predefined predicate.
Perhaps something as simple as a `writeLibraries` boolean. If this was done by default then the user would only provide the options to disable -- but this breaks current behaviour so is probably undesirable.

## Proposal 2

Add a convenient function to strip out library content (referenced content). Something like this:
```python
def removeReferencedElements(doc):
    """
    Remove any elements which are referenced in. That is has a source URI.
    """
    for elem in doc.getChildren():
        if elem.hasSourceUri():
            doc.removeChild(elem.getName())
```

(The alternative of keeping reference documents for standard libraries -- which would mean there is nothing to prune
has already been proposed but no design has been finalized currently).

**Comment by jstone-lucasfilm** [comment]
Let me know your thoughts, @kwokcb, but I believe this has effectively been addressed by @ashwinbhat's work on data library referencing, as applications using this new pattern have an automatic separation of content and library documents when writing out XML:

https://github.com/AcademySoftwareFoundation/MaterialX/pull/2054

**Comment by kwokcb** [comment]
There is still the case you can import libraries but hopefully as folks switch over to the new API this case will occur much less often. 
 Let's close this out.
