### ISSUE TITLE
MaterialX Viewer: Add a help UI

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#2011]
## Proposal

Add UI to show help for the MaterialX Viewer. Especially for hidden hot keys which folks may not know about:

https://github.com/AcademySoftwareFoundation/MaterialX/blob/64b96968ef2432a542defe5fa8b365c467d97ed0/documents/DeveloperGuide/Viewer.md?plain=1#L60

Adding help for the menus would also be useful but is more obvious.

This would match how the graph editor has help for such things.

**Comment by juandejoya** [comment]
Would it be okay for me to contribute to this ticket as part of Dev Days?

**Comment by jstone-lucasfilm** [comment]
That would be excellent, thanks @juandejoya!

**Comment by jstone-lucasfilm** [comment]
Thanks to @kwokcb for this original proposal, and to @juandejoya for the implementation in #2026!
