### ISSUE TITLE
Add MaterialX Python to PyPi

### ISSUE THREAD

**Issue by jstone-lucasfilm** [AcademySoftwareFoundation/MaterialX#570]
Add the MaterialX Python library to the PyPi registry, making it available from the command line via "pip install" on Windows, Linux, and MacOS.  Some starting references may be found below:

https://pypi.org/
https://github.com/pybind/python_example

**Comment by meshula** [comment]
And Conda, while you're at it :)

**Comment by JeanChristopheMorinPerso** [comment]
Here is a small list of ASWF examples:
* https://github.com/AcademySoftwareFoundation/OpenTimelineIO/blob/main/setup.py
* https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/setup.py
* https://github.com/OpenAssetIO/OpenAssetIO/blob/main/setup.py

The general idea is to run the build from the `setup.py`. I'll be more than happy to help if needed.

**Comment by TRohit20** [comment]
Hey everyone, Can the project maintainers assign this issue to me so I can get the task done and open a PR resolving the same. Thank you.

**Comment by jstone-lucasfilm** [comment]
That would be much appreciated, @TRohit20!  Let's check with @kwokcb and @JeanChristopheMorinPerso before proceeding, since they have expressed interest in this feature as well, but otherwise I would have no reservations about assigning the issue to you.

**Comment by TRohit20** [comment]
Awesome, Looking forward to work on it if it gets assigned

**Comment by jstone-lucasfilm** [comment]
Thanks for offering to take this on, @TRohit20, and feel free to reach out to @JeanChristopheMorinPerso, @kwokcb, or me if you have questions!

**Comment by TRohit20** [comment]
Sure thing, I will get started from tomorrow!

**Comment by jstone-lucasfilm** [comment]
@TRohit20 Just checking in on this GitHub Issue, to see if you've had a chance to take an initial look.  We've incorporated a couple of improvements to our Python package in preparation for MaterialX 1.38.7, and these could end up being helpful in integrating MaterialX with PyPi as well:

https://github.com/AcademySoftwareFoundation/MaterialX/pull/1237
https://github.com/AcademySoftwareFoundation/MaterialX/pull/1313

**Comment by JeanChristopheMorinPerso** [comment]
I created a PR: https://github.com/AcademySoftwareFoundation/MaterialX/pull/1317
