### ISSUE TITLE
Material isn't getting applied

### ISSUE THREAD

**Issue by numega** [AcademySoftwareFoundation/MaterialX#620]
I believe the following file should lead to a green object in MaterialXView, but right now I get a black object. Additionally, I see the following output: "OpenGL error after program unbind geometry: 1282". If I replace the `interfacename="colorA"` and `interfacename="colorB"` lines with a value then everything shows up properly.

```
<?xml version="1.0"?>
<materialx version="1.38" colorspace="lin_rec709">
    <nodedef name="NG_mymaterial" node="mymaterial">
        <input name="colorA" type="color3" value="0, 0.5, 0"/>
        <input name="colorB" type="color3" value="0, 0.5, 0"/>
        <output name="out" type="material"/>
    </nodedef>
    <nodegraph name="blah" nodedef="NG_mymaterial">
        <add name="add1" type="color3">
            <input name="in1" type="color3" interfacename="colorA"/>
            <input name="in2" type="color3" interfacename="colorB"/>
        </add>
        <UsdPreviewSurface name="SR_default" type="surfaceshader">
            <input name="diffuseColor" type="color3" nodename="add1"/>
        </UsdPreviewSurface>
        <surfacematerial name="m1" type="material">
            <input name="surfaceshader" type="surfaceshader" nodename="SR_default"/>
        </surfacematerial>
        <output name="out" type="material" nodename="m1"/>
    </nodegraph>
    <mymaterial name="Material1" type="material"/>
</materialx>
```

**Comment by numega** [comment]
The OpenGL error is due to GlslProgram::unbindGeometry() being called for each assignment of the material. You can reproduce this issue with the shaderball.obj file in resources/Geometry. As a workaround I added the following at the beginning of the function:

```
void GlslProgram::unbindGeometry()
{
    if (_vertexArray == GlslProgram::UNDEFINED_OPENGL_RESOURCE_ID)
        return;

    glBindVertexArray(_vertexArray);

```

**Comment by bernardkwok** [comment]
What you have should show up green without modification. 

From an initial look, it appears to be an issue with having the `<surfacematerial>` in the nodegraph definition not picking up the default values properly for code generation. 

For example this does pick up default values properly:
```
<?xml version="1.0"?>
<materialx version="1.38" colorspace="lin_rec709">
  <nodedef name="NG_mymaterial" node="mymaterial">
    <input name="colorA" type="color3" value="0, 0.5, 0" />
    <input name="colorB" type="color3" value="0, 0.5, 0" />
    <output name="out" type="surfaceshader" />
  </nodedef>
  <nodegraph name="blah" nodedef="NG_mymaterial" >
    <add name="add1" type="color3" nodedef="ND_add_color3">
      <input name="in1" type="color3" interfacename="colorA" />
      <input name="in2" type="color3" interfacename="colorB" />
    </add>
    <UsdPreviewSurface name="SR_default" type="surfaceshader">
        <input name="diffuseColor" type="color3" nodename="add1"/>
    </UsdPreviewSurface>
    <output name="out" type="surfaceshader" nodename="SR_default" />
  </nodegraph>
  <mymaterial name="Material1" type="surfaceshader" />
  <output name="test" nodename="Material1" type="surfaceshader" />
</materialx>
```

**Comment by niklasharrysson** [comment]
Just some more info from debugging this: 

The problem is that when finding renderable elements in a document, for materials we dig into it and extract the surfaceshader connected inside/upstream. So in this case we extract the UsdPreviewSurface from inside the materials implementation graph and generate code for that. The problem is that we then lose all information about what is connected or set on the materials interface.

So we need to treat materials as renderable elements explicitly, without extracting their shaders. And as part of this we need to add support for code generation of material elements, including having materials implemented as graphs.

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @numega, and thanks to @niklasharrysson for addressing it in #981!
