### ISSUE TITLE
Exporting to glTF2 PBR material and glTF2 material with sheen, clearcoat and transmission.

### ISSUE THREAD

**Issue by fire** [AcademySoftwareFoundation/MaterialX#653]
Trying to devise a match for the gltf2:

1. glTF2 PBR materials
2. glTF2 material with sheen, clearcoat and transmission.

Not sure where the current work is.

**Comment by jstone-lucasfilm** [comment]
@fire To my mind, the first step would be the creation of a MaterialX graph for the glTF BSDF, which should be validated by Khronos then contributed to the BxDF graph library in MaterialX:

https://github.com/materialx/MaterialX/tree/main/libraries#bxdf-graph-library

We're happy to help developers in constructing such a graph, and there are several examples from which they can borrow, but ideally the development process should be overseen by the designers of the glTF BSDF at Khronos.

**Comment by fire** [comment]
I have started initial contact with Khronos's gltf working group.

**Comment by emackey** [comment]
One of the members of the Khronos PBR TSG began prototyping something for us to experiment with.  Many things still need adding or fixing, but it's a great start:

https://github.com/KhronosGroup/MaterialX/commit/3d85657846be0f89e720a7752c87878f387896a9

**Comment by fire** [comment]
Reporting back that I was able to compile gltf2 boombook example and using previous standalone work I was able to bake the dependencies.

![boom_box_bake](https://user-images.githubusercontent.com/32321/130652372-1568f8ec-716b-4f8a-8fdc-d63233a71f0f.png)
![boombox_viewer](https://user-images.githubusercontent.com/32321/130652373-9e47bc2c-7c14-4eb6-8f47-6d93dee3e210.png)

https://github.com/fire/MaterialX/tree/standalone-gltf

**Comment by fire** [comment]
@donmccurdy gave me some MaterialX sample to reference making pbr gltf materials.

1. https://github.com/donmccurdy/three.js/blob/364bf554d47ed92ea76a2630f4c602ee76b993d6/examples/jsm/loaders/MaterialXLoader.js#L259-L273

**Comment by jstone-lucasfilm** [comment]
An initial MaterialX graph for the glTF PBR shading model has been merged in pull request #861.

**Comment by jstone-lucasfilm** [comment]
Thanks for posting this original issue, @fire, and I believe we can close it out and create new issues (e.g. #874) to capture additional work on glTF/MaterialX integration.
