### ISSUE TITLE
Windows MaterialXView paths not working?

### ISSUE THREAD

**Issue by emackey** [AcademySoftwareFoundation/MaterialX#671]
Hopefully I'm not making some obvious mistake, but I tried building MaterialXView for Win x64 from the head of `main` today, and running it with the repo root as current working folder.  I get some path errors, where it tries to read GLSL files from paths that appear to be missing `libraries` on the front.  For example:

> Failed to generate environment shader: Failed to get source code from file 'stdlib\genglsl\mx_image_color3.glsl' used by implementation 'IM_image_color3_genglsl'
Failed to generate wireframe shader: Failed to get source code from file 'stdlib\genglsl\mx_constant.inline' used by implementation 'IM_constant_color3_genglsl'
Failed to generate shadow shader: Failed to get source code from file 'stdlib\genglsl\mx_constant.inline' used by implementation 'IM_constant_color3_genglsl'
Failed to generate shadow blur shader: Failed to get source code from file 'stdlib\genglsl\mx_image_color3.glsl' used by implementation 'IM_image_color3_genglsl'
Caught exception in main loop: Failed to get source code from file 'stdlib\genglsl\mx_constant.inline' used by implementation 'IM_constant_color3_genglsl'

In the above, the string `'stdlib\genglsl\mx_image_color3.glsl'` apparently should be `'libraries\stdlib\genglsl\mx_image_color3.glsl'`. Did I do something wrong?

**Comment by jstone-lucasfilm** [comment]
@bernardkwok One idea for the future, which might address this category of potential errors, is to remove the hardcoded assumption that source code is within a "libraries" folder.  We could add this prefix explicitly to the existing paths and #include directives in our data libraries, and remove the string from the code generation modules in C++.

**Comment by jstone-lucasfilm** [comment]
I've written up a pull request for the change described above, which should make it less likely for this category of error to occur in the future:

https://github.com/AcademySoftwareFoundation/MaterialX/pull/877

**Comment by jstone-lucasfilm** [comment]
Thanks for the original report, @emackey, and I believe this has been addressed in #877.  Feel free to open a new issue if you run into similar issues in the future.
