### ISSUE TITLE
Document MaterialX mimetype

### ISSUE THREAD

**Issue by fire** [AcademySoftwareFoundation/MaterialX#682]
Can documentation for the MaterialX mimetype be written?

Possible options are `image/mtlx` and `image/materialx`

**Comment by jstone-lucasfilm** [comment]
I believe this should technically be possible, but I'd be curious as to what benefits this would provide to developers or artists working with MaterialX content.  Did you have a specific use case in mind?

**Comment by fire** [comment]
Let me write up the details, the simplest example was I wanted to include into gltf like png. Might require a single xml doc though and of course I could use the xml mimetype

**Comment by fire** [comment]
prior art.

svg has a external mode where there is a avg and external files like svg and png or svgz which is a singular file.

**Comment by meshula** [comment]
The mimetype precedent for material files is the Wavefront MTL file. Its mimetype is `model/mtl`. Reasonable mimetypes would include `model/matx`, `model/material-x`, and the like.

https://www.digipres.org/formats/mime-types/

**Comment by jstone-lucasfilm** [comment]
@fire I'll close this issue for now, but we're open to future discussions in this area.
