### ISSUE TITLE
Add the ability to query document information

### ISSUE THREAD

**Issue by bernardkwok** [AcademySoftwareFoundation/MaterialX#701]
This is a request to have a read api which can return only the document level
information without loading in the file.

One use case is to find out the current version information. This is currently not possible after a
regular read as an automatic upgrade is performed. Perhaps one option would be to return an empty
document with all the document attributes set. Then any information including version, color config, etc could be 
extracted out using regular methods. 

An alternative could be to provide original information back during the existing read interfaces but
this seems more like a patch workaround.

**Comment by jstone-lucasfilm** [comment]
@bernardkwok With pull request #775, we now have the ability to load a document without upgrading its version, allowing the on-disk version of the document to be queried.  Does that seem like a reasonable approach for the use case you propose here?

**Comment by jstone-lucasfilm** [comment]
I'll close out this issue for now, as I believe it ought to be resolved by the pull request above, but feel free to open a new issue if it doesn't cover all cases.
