### ISSUE TITLE
Should opacity input on node "surface" be color instead of float

### ISSUE THREAD

**Issue by niklasharrysson** [AcademySoftwareFoundation/MaterialX#712]
As pointed out by @code-monkey in this issue (https://github.com/Autodesk/standard-surface/issues/20), the `surface` node in MaterialX pbrlib only supports monochromatic opacity with a float input. In order to support colored opacity we should consider chaining this to a color3 input.

**Comment by jstone-lucasfilm** [comment]
Following up on this thread in 2024, I believe Niklas makes a good case above for handling colored shadows using a technique other than colored opacity, and I'll note that the new OpenPBR Surface aligns with MaterialX in using simple float values for opacity.

We're still open to additional discussion on this topic, but for now I'll mark this issue as resolved pending further proposals.
