### ISSUE TITLE
Transmission support for generalized_schlick_bsdf

### ISSUE THREAD

**Issue by niklasharrysson** [AcademySoftwareFoundation/MaterialX#713]
The `generalized_schlick_bsdf` node is missing support for transmission in GLSL and OSL.

Marked with TODO's in code here:
https://github.com/materialx/MaterialX/blob/main/libraries/pbrlib/genglsl/mx_generalized_schlick_bsdf.glsl#L41
https://github.com/materialx/MaterialX/blob/main/libraries/pbrlib/genosl/mx_generalized_schlick_bsdf.osl#L6
 
For MDL it's already supported.

Linking this issue to the following PR in glTF that reported this problem: 
https://github.com/KhronosGroup/MaterialX/pull/1

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @niklasharrysson, and this has been addressed in #918 (GLSL) and #934 (OSL).
