### ISSUE TITLE
Color to float conversion for directional albedo in generalized_schlick_bsdf

### ISSUE THREAD

**Issue by niklasharrysson** [AcademySoftwareFoundation/MaterialX#714]
We use the color component average to convert directional albedo to a monochromatic value in `generalized_schlick_bsdf`.

Conversion is done to avoid getting complementary colors on the base layer. But the use of average may in some cases result in issues with energy conservation for separate color components, as noted in this PR: https://github.com/KhronosGroup/MaterialX/pull/1

A possible strategy to avoid this is to use the max value of the color components instead of the average.

We should here discuss the pros and cons of these strategies (or others?).

**Comment by jstone-lucasfilm** [comment]
For now, I believe the averaging of directional albedo in layering computations is our best available option for `generalized_schlick_bsdf`, so I'll close out this original issue.

Feel free to reopen this, though, if a new proposal appears to have a significant advantage over our current one.

As a reference for future readers, here is the GLSL code where the averaging of directional albedo is currently used in layering for `generalized_schlick_bsdf`:

https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/libraries/pbrlib/genglsl/mx_generalized_schlick_bsdf.glsl#L42
