### ISSUE TITLE
Update OSL code generator to handle std and custom type conflicts  

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#781]
The OSL code generator currently is incomplete in it's restrictions list for identifier conflicts.
All standard OSL types as well as any custom types added by the generator should be
added to the OSLSyntax restricted list to avoid usage of restricted identifiers in the code.

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @kwokcb, and the standard types have been added in #1090.  Let's close out this broader task, and we can add a more specific task to handle custom types if needed.
