### ISSUE TITLE
Standard surface implementation of specular transmission does not handle thin_walled

### ISSUE THREAD

**Issue by dleex** [AcademySoftwareFoundation/MaterialX#795]
According to https://autodesk.github.io/standard-surface/
"thin_walled" parameter is used to affect both specular (section 3.6) and diffuse (section 3.9) behaviour - the current implementation only handles the diffuse part where it's switching between diffuse and subsurface scatter, but not the specular transmission where it sets refraction IOR to 1.0 and disable dispersion and thin film.

**Comment by jstone-lucasfilm** [comment]
Thanks for this original report, @dleex, and I'm merging it with the broader topic in #864.
