### ISSUE TITLE
Improved ramp support?

### ISSUE THREAD

**Issue by BrianHanke** [AcademySoftwareFoundation/MaterialX#797]
Howdy, I'm using MaterialX in Houdini Karma and I'm very pleased with the system overall. The only thing I find lacking are the native MatX ramp nodes. To address this, SideFX released their own ramps along with Houdini 19. However, their solution isn't portable to other apps. Are there plans to make a more feature-complete native ramp that will work in all MatX-enabled apps? Thank you!

**Comment by swillisart** [comment]
Hey! It's a planned feature for v1.39. 

https://github.com/materialx/MaterialX/issues/674#issuecomment-985156797

(copied from the slack channel)
> MaterialX TSC Minutes - Tuesday, November 9th
> Custom ramp nodes in Houdini are implemented as MaterialX graphs, making them portable and forward-compatible
> We should combine the best aspects of Houdini ramps and MaterialX v1.38 ramps (specification only) for the upcoming MaterialX v1.39

**Comment by BrianHanke** [comment]
Awesome, glad to hear it!

**Comment by jstone-lucasfilm** [comment]
Merging this issue with the earlier #674 for tracking, and I'll note that the topic was discussed further at today's MaterialX TSC meeting:

https://academysoftwarefdn.slack.com/archives/C0230LWBE2X/p1655837092353349
