### ISSUE TITLE
Suggestions: For shader reference generation

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#832]
The following are some suggestions on improvements to shader reference generation.

0. Always emit OSL metadata indicating the definition name for easy back-tracing.
![image](https://user-images.githubusercontent.com/49369885/152993948-31a14728-75ba-40ec-a93b-8796c4a6f47a.png)
1. Move reference generation logic out of test so it can be run as a utility by anyone. (Test code does not ship as part of package)
2. Update reference generation for OSL.
3. Generalize to be able to generate references for any language.
4. Generate either full shaders or just functions.
5. Add infrastructure to perform render testing vs just compile testing ?

Tangential to options, is to improve deployment by extending to allow check-in as part of core code. The github action creates zip but in only available as CI download and not part of the package).

**Comment by jstone-lucasfilm** [comment]
Closing this earlier issue in favor of the more recent proposals in #1000.
