### ISSUE TITLE
The nodegraph for Range is incorrect in stdlib_ng.mtlx

### ISSUE THREAD

**Issue by numega** [AcademySoftwareFoundation/MaterialX#863]
The clamp node should use outlow and outhigh. Right now it's just using the default range ([0-1]).

**Comment by jstone-lucasfilm** [comment]
Good catch, @numega, and I agree with your earlier proposals for stdlib as well.  We'd appreciate any fixes that your team has the bandwidth to contribute, and otherwise we'll plan to take a look on our side.

**Comment by jstone-lucasfilm** [comment]
I had a chance to look into this one, and have posted pull request #866 with a fix.

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @numega, and the fix is now merged.
