### ISSUE TITLE
The nodegraph for ramp4 is incorrect

### ISSUE THREAD

**Issue by numega** [AcademySoftwareFoundation/MaterialX#872]
According to the supplemental spec, a texcoord value of (0, 0) should return the bottom left value. However, the current graph will return the top left value. I think that the arguments to the last mix node should be reversed.

**Comment by jstone-lucasfilm** [comment]
Good observation, @numega, and feel free to post a fix if your team has the bandwidth and necessary approvals.

**Comment by jstone-lucasfilm** [comment]
Let's close out this issue in favor of #1758, which has a slightly broader scope.

Thanks to @numega for this original report!
