### ISSUE TITLE
Performance: Getting definition from node always requires full cache rebuild

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#876]
The method to get a definition (`getNodeDef()`) from a node as it requires a signature match. The only workaround is to add in a corresponding "nodedef" on the specified node. 

One reason it is slow is that anytime the cache is marked dirty for any reason then it needs to be rebuilt, and the signature matching code requires an up-to-date match.

Perhaps an optimization is to only rebuild the cache logic matching if a node definition changes (which should be fairly uncommon).

As an example, the follow code is almost unusable with setting the `nodedef` before hand. Tested with about 100 calls to add inputs from a nodedef to a newly created node. Here `copyContentFrom()` and `removeAttribute()` dirty the cache but these operations have no relation to definition signature matching which requires a cache rebuild when called from `getNodeDef()`.
```
void addDefaultInputs(NodePtr& shaderNode)
{
    StringVec nonInstanceAttributes = { ValueElement::DOC_ATTRIBUTE, ValueElement::INTERFACE_NAME_ATTRIBUTE,
                                        ValueElement::ENUM_ATTRIBUTE, ValueElement::ENUM_VALUES_ATTRIBUTE, 
                                        ValueElement::UI_NAME_ATTRIBUTE, ValueElement::UI_FOLDER_ATTRIBUTE, ValueElement::UI_MIN_ATTRIBUTE,
                                        ValueElement::UI_MAX_ATTRIBUTE, ValueElement::UI_SOFT_MIN_ATTRIBUTE, ValueElement::UI_SOFT_MAX_ATTRIBUTE,
                                        ValueElement::UI_STEP_ATTRIBUTE, ValueElement::UI_ADVANCED_ATTRIBUTE, ValueElement::UNIFORM_ATTRIBUTE };

    NodeDefPtr nodeNodeDef = shaderNode->getNodeDef();
    if (nodeNodeDef)
    {
        for (ValueElementPtr nodeDefValueElem : nodeNodeDef->getActiveValueElements())
        {
            const std::string& valueElemName = nodeDefValueElem->getName();
            InputPtr nodeInput = shaderNode->getInput(valueElemName);
            if (!nodeInput)
            {
                InputPtr nodeDefInput = nodeNodeDef->getActiveInput(valueElemName);
                if (nodeDefInput)
                {
                    nodeInput = shaderNode->addInput(nodeDefInput->getName());
                    nodeInput->copyContentFrom(nodeDefInput);
                    for (auto nonInstanceAttribute : nonInstanceAttributes)
                    {
                        nodeInput->removeAttribute(nonInstanceAttribute);
                    }
                }
            }
        }
    }
}
```

**Comment by jstone-lucasfilm** [comment]
@kwokcb Improving the document caching scheme is a worthwhile area for discussion, though we'd want to be sure that the performance benefits in real-world scenarios are worth the additional complexity.  In the past, we've usually found alternative strategies for implementing algorithms that avoid the interleaved reads and writes of the code above, removing the need for more sophisticated caching.  In your example, I believe you ended up finding a simpler approach that was more efficient, but I'm open to returning our focus to caching improvements if we run into real-world cases that cannot easily be simplified in this way.

**Comment by jstone-lucasfilm** [comment]
I'll close out this issue for now, but feel free to propose caching optimizations as needed in the future.
