### ISSUE TITLE
setSourceCode 'const' type qualifier on return type has no effect

### ISSUE THREAD

**Issue by fire** [AcademySoftwareFoundation/MaterialX#880]
https://github.com/AcademySoftwareFoundation/MaterialX/blob/main/source/MaterialXGenShader/Shader.h#L98

MaterialXGenShader/Shader.h:98:5: error: 'const' type qualifier on return type has no effect [-Werror,-Wignored-qualifiers]

Expected behaviour:

Removed the const on the void.

**Comment by jstone-lucasfilm** [comment]
This is a good note, and feel free to address the issue if you have the bandwidth!

**Comment by jstone-lucasfilm** [comment]
Thanks for this report, @fire, and this has been addressed in pull request #887.
