### ISSUE TITLE
I'm not sure

### ISSUE THREAD

**Issue by Jinjinkun** [AcademySoftwareFoundation/MaterialX#903]
#include <iostream>

uisng namespace std;

int main(){
  int n;
  do{
  cout << "加算する回数を整数値で入力:";
  cin >> n;
  }while(n <= 0)
  
  int sum = 0;

for(int i = 0; i < n; i++){
   int x;
   cout << "加算する値を入力:";
   cin >> x;
   
   sum += x;
   }
   cout << "合計値は" << sum << "です。\n";
}

**Comment by jstone-lucasfilm** [comment]
@Jinjinkun Are you suggesting that MaterialX ought to support a loop node?  ;)
