### ISSUE TITLE
Thin-film with metallic base in standard surface implementation

### ISSUE THREAD

**Issue by dleex** [AcademySoftwareFoundation/MaterialX#922]
It seems "thin_film_bsdf" is layerd on top of "specular_layer" then mixed with "metal_bsdf" (with "metalness") afterwards, so 100% metallic material won't have any thin-film. But according to the [spec](https://autodesk.github.io/standard-surface/), "thin-film logically sits between the coat and underlying layer" so it should be possible to have thin-film with metallic base.

**Comment by niklasharrysson** [comment]
Good catch @dleex! We previously didn't support having "thin_film_bsdf" applied to a mix of BSDF nodes, but this was resolved in #747 . So I just missed to update the nodegraph for Standard Surface to use this. Should be easy to resolve. Thanks for reporting it.

**Comment by jstone-lucasfilm** [comment]
Thanks to @dleex for this report, and to @niklasharrysson for the fix!
