### ISSUE TITLE
Definition Proposal : Allow interpretation option for input color for <image> nodes

### ISSUE THREAD

**Issue by kwokcb** [AcademySoftwareFoundation/MaterialX#933]
# Proposal
Allow for color blending as part of `<image>` node definition.

# Affected nodes:
`<image>` and definitions using this node definition.

# Existing
Currently there is a "default color" which is used for unmapped areas or if an image cannot be found.

# Change proposed
* Allow for this color to be used to blend with the input texture. The default would be not affect the texture 
* The operation occurs after the texture lookup -- thus after any color space transformation.
* The blend can be a fixed a set of enumerations (e.g. none, modulate, etc)
* The color input is connectable and allow to have a geometry semantic / geometry property to allow for geometric blending.
* Unmapped areas would still be a color replacement.

This would propagate to be exposable on definitions using the base `<image>` including `tiledimage`.

**Comment by dbsmythe** [comment]
What would be used to control the blend amount?  The alpha of the image?  What if the texture doesn't have an alpha channel?
Can you elaborate on "The color input is connectable and allow to have a geometry semantic / geometry property to allow for geometric blending"?  I assume by this you mean the "default" color input?  What do you mean by "geometric blending"?

Note: my gut instinct is that the <image> node should remain simple and unchanged, and that any additional functionality be created using a new supplemental node type with a nodegraph implementation.

**Comment by jstone-lucasfilm** [comment]
@kwokcb I would agree with Doug here, and it seems preferable for <image> to remain the simplest possible primitive, with any additional blending operations being implemented as graph-based nodes containing this primitive.

**Comment by jstone-lucasfilm** [comment]
I'll close out this issue for now, but it's worthwhile to discuss graph-based mechanisms for handling this functionality in the future.

**Comment by kwokcb** [comment]
Sorry for the delay in updating this. 

It makes sense to keep <image> as simple as possible and make this a new graph / nodedef.

@dbsmythe for your queries:
* Blending can be controlled by alpha on the input color or image color. alpha=1 if color3.
* For color connection, basically you can tag it as with an default geometry property, or use an upstream geometry node which would be allowable considering the next point:
* For default color, this actually doesn't really properly map to all shading language image calls such as for OSL which have apis which specific such things as a "black" default. So IMHO it's more of a "base" color. If thought of as that then the option is how to combine base with the image.
