### ISSUE TITLE
ND_range_color4 applies gamma to all channels

### ISSUE THREAD

**Issue by numega** [AcademySoftwareFoundation/MaterialX#954]
Currently, the nodegraph for ND_range_color4 applies the gamma value to all channels (including the alpha channel). Should this be changed to only the rgb channels?

**Comment by dbsmythe** [comment]
If you provide a float value for "gamma", the more consistent-with-other-operations result would be to apply it to all four channels, including alpha, e.g. the current behavior, which I think would actually be the desired behavior in many (most?) cases if the RGBA is a premultipled (matted-to-black) color.  If the desired result is to apply a gamma to just RGB and not to Alpha, you should be able to provide a four-channel color4 "gamma" value (gamma, gamma, gamma, 1.0) to do what you're asking.

**Comment by jstone-lucasfilm** [comment]
@numega @dbsmythe I'll close out this issue, since the current behavior seems correct, but feel free to write up new issues as needed.
